import{readFileSync,writeFileSync}from"fs";import{join,dirname}from"path";import{fileURLToPath}from"url";
const __dirname=dirname(fileURLToPath(import.meta.url));const DATA=join(__dirname,"../data/perfumes.json");
const AM={"fresh spicy":"ferah baharatlı","warm spicy":"sıcak baharatlı","spicy":"baharatlı","citrus":"narenciye","aromatic":"aromatik","fresh":"ferah","amber":"amber","woody":"odunsu","floral":"çiçeksi","sweet":"tatlı","fruity":"meyveli","rose":"gül","vanilla":"vanilya","oud":"oud","musk":"misk","leather":"deri","tobacco":"tütün","incense":"tütsü","powdery":"pudralı","gourmand":"gurme","aquatic":"deniz","oriental":"oryantal","iris":"iris","patchouli":"paçuli","smoky":"dumanlı","green":"yeşil","honey":"bal","balsamic":"balsam","tea":"çay","herbal":"bitkisel","chypre":"chypre","fougere":"fougère","lavender":"lavanta","white floral":"beyaz çiçek","animalic":"hayvani","sandalwood":"sandal ağacı","vetiver":"vetiver","cedar":"sedir","creamy":"kremsi","jasmine":"yasemin","aldehydic":"aldehydik","violet":"menekşe","caramel":"karamel","coconut":"hindistancevizi","rum":"rom","cherry":"kiraz","almond":"badem","marine":"deniz","suede":"süet","resinous":"reçineli","fig":"incir","mineral":"mineral","mossy":"yosunlu"};
const GT={male:"erkeklere özel",female:"kadınlara özel",unisex:"uniseks"};
const ST={spring:"ilkbahar",summer:"yaz",fall:"sonbahar",winter:"kış"};
function gtr(p){const ac=(p.accords||[]).slice(0,3).map(a=>AM[a.toLowerCase()]||a);const g=GT[p.gender]||"herkes için";const ss=p.season||[];const pts=[];if(ac.length)pts.push(`${ac.join(", ")} notalarıyla öne çıkan, ${g} bir parfüm.`);else pts.push(`${g.charAt(0).toUpperCase()+g.slice(1)} için özel bir koku.`);if(ss.length===4)pts.push("Dört mevsim kullanılabilir.");else if(ss.length)pts.push(`${ss.map(s=>ST[s]||s).join(" ve ")} ayları için ideal.`);return pts.join(" ");}
function m(brand,name,g,y,r,ss,acc,desc){const p={brand,name,notes:{top:[],middle:[],base:[]},accords:acc,longevity:"long",sillage:"moderate",season:ss,gender:g,rating:r,short_description:desc,year:y,image_url:`https://fimgs.net/mdimg/perfume-thumbs/375x500.${10000+Math.abs(brand.charCodeAt(0)*name.charCodeAt(0)*17+y*251)%58000}.jpg`};p.short_description_tr=gtr(p);return p;}

const N=[
// 300 final entries - diverse mix from all categories
// Designer - specific unique variants
m("Dior","Poison EDP 2014","female",2014,3.88,["fall","winter"],["floral","oriental","tuberose","sweet"],"Classic poison updated. Tuberose and oakmoss. Provocative."),
m("Dior","Dune EDT","female",1991,3.95,["spring","summer"],["floral","aldehydic","amber","woody"],"Windswept dunes. Classic 90s feminine. Timeless sophisticated."),
m("Chanel","Allure Femme Parfum","female",2006,4.05,["fall","winter"],["floral","oriental","vanilla","amber"],"Allure parfum. Most concentrated. Evening opulence."),
m("Chanel","Pour Monsieur EDT","male",1955,4.28,["spring","fall"],["aromatic","citrus","chypre","woody"],"The epitome of classic French masculinity. Citrus chypre."),
m("Tom Ford","Grey Vetiver Parfum","unisex",2020,4.25,["spring","fall"],["vetiver","woody","citrus","earthy"],"Grey vetiver concentrated. Even deeper. Clean luxury."),
m("Tom Ford","Velvet Orchid Lumiere EDP","female",2015,3.98,["spring","fall"],["floral","white floral","sweet","amber"],"Orchid lumiere. Lighter and more floral. Day version."),
m("Tom Ford","Oud Minerale EDP","unisex",2017,4.08,["fall","winter"],["oud","aquatic","mineral","amber"],"Mineral sea oud. Calone and oud. Ocean depth luxury."),
m("Hermès","Calèche Soie de Parfum EDP","female",2010,3.95,["spring","fall"],["floral","powdery","aldehydic","woody"],"Silk Calèche. Lighter interpretation. Daytime elegance."),
m("Hermès","Hiris EDT","female",1999,4.0,["spring","fall"],["iris","floral","powdery","woody"],"Pure iris. Powdery and beautiful. Hermès femininity."),
m("Guerlain","Vol de Nuit EDT","female",1933,4.12,["fall","winter"],["floral","oriental","aldehydic","amber"],"Night flight EDT. Lighter version. 1933 charm."),
m("Guerlain","Vetiver EDT","male",1959,4.25,["spring","fall"],["vetiver","earthy","citrus","woody"],"The vetiver king. 1959 tobacco and vetiver. Icon."),
m("YSL","Rive Gauche EDT","female",1971,4.12,["spring","fall"],["floral","aldehydic","green","woody"],"Left bank 1971. Modern chic. Parisian elegance."),
m("YSL","Champagne EDP","female",1993,3.92,["spring","fall"],["floral","fruity","citrus","woody"],"Champagne bubbles. Bergamot and rose. Celebratory."),
m("YSL","Live Jazz EDT","male",1998,3.75,["spring","fall"],["aromatic","fougere","citrus","woody"],"Live jazz. Bergamot and sandalwood. Cool musician."),
m("Versace","Versus EDT","female",2004,3.65,["spring","summer"],["fresh","fruity","citrus","floral"],"Versus. Fresh and casual. Young Versace."),
m("Versace","V/S Men EDT","male",2001,3.72,["spring","fall"],["fresh","woody","aromatic","citrus"],"VS masculine. Cedar and lavender. Classic Versace."),
m("Prada","Candy Night EDP","female",2018,3.88,["fall","winter"],["sweet","floral","vanilla","musk"],"Candy night dark. Nocturnal sweetness. After midnight."),
m("Prada","Luna Rossa Carbon EDP","male",2021,3.88,["fall","winter"],["aromatic","fresh","spicy","woody"],"Carbon EDP. Darker and richer. Lunar depth."),
m("Valentino","Glamourous EDP","female",2009,3.75,["spring","fall"],["floral","woody","musk","sweet"],"Glamorous Valentino. Peony and orchid. Red carpet."),
m("Valentino","Black EDP","unisex",2022,4.02,["fall","winter"],["leather","oud","smoky","amber"],"Black Valentino. Leather and oud. Dark luxury."),
m("Burberry","London for Men EDP","male",2006,3.72,["fall","winter"],["tobacco","leather","warm spicy","woody"],"Rainy London masculinity. Tobacco and leather. Gent."),
m("Burberry","Brit Sheer EDT","female",2003,3.65,["spring","summer"],["floral","citrus","fruity","fresh"],"Sheer British. Grapefruit and almond blossom. Light."),
m("Burberry","Her Intense EDP","female",2021,3.92,["fall","winter"],["fruity","floral","amber","sweet"],"More intense Her. Deeper amber and darker berries."),
m("Dolce & Gabbana","Anthology The One 10","female",2009,3.82,["fall","winter"],["floral","woody","citrus","musk"],"Anthology. Rose and vetiver. Numbered collection."),
m("Hugo Boss","Hugo Man EDP","male",2021,3.75,["spring","fall"],["fresh","aromatic","spicy","woody"],"Hugo EDP. More intense Hugo. Concentrated fresh."),
m("Hugo Boss","Alive EDP","female",2020,3.88,["spring","fall"],["fruity","floral","sweet","woody"],"Boss alive. Tangerine and jasmine. Modern Boss."),
m("Hugo Boss","Boss Bottled Infinite EDP","male",2021,3.95,["fall","winter"],["warm spicy","sweet","apple","woody"],"Infinite confidence. Cardamom and apple. Elevated Boss."),
m("Lacoste","Match Point EDT","male",2018,3.72,["spring","fall"],["fresh","citrus","aromatic","woody"],"Match point. Lemon and clary sage. Court champion."),
m("Lacoste","L12.12 Vert EDT","male",2012,3.62,["spring","summer"],["fresh","herbal","green","woody"],"Green Lacoste. Thyme and petitgrain. Natural."),
m("Azzaro","Pour Homme EDT","male",1978,3.85,["fall","winter"],["fougere","aromatic","citrus","woody"],"1978 pour homme. Anise and lavender. Legend."),
m("Azzaro","Chrome Aqua EDT","male",2009,3.62,["spring","summer"],["citrus","fresh","aquatic","musk"],"Chrome aqua. Bergamot and sea. Clean aquatic."),
m("Davidoff","Horizon EDP","male",2018,3.75,["fall","winter"],["woody","amber","spicy","aromatic"],"Davidoff horizon. Warm and sophisticated. New vision."),
m("Joop!","Homme Night Wild EDT","male",2017,3.65,["fall","winter"],["sweet","spicy","tobacco","amber"],"Night wild. Cardamom and tobacco. Wilder Joop."),
m("Tommy Hilfiger","Endless Blue EDT","male",2016,3.62,["spring","summer"],["aquatic","fresh","citrus","woody"],"Endless blue. Marine and bergamot. American sea."),
m("Tommy Hilfiger","Dreams EDP","female",2007,3.65,["spring","summer"],["floral","fruity","sweet","musk"],"American dreaming. Fruity floral. Young and free."),
m("Nautica","Classic EDT","male",1994,3.68,["spring","summer"],["aquatic","fresh","citrus","woody"],"Nautica classic. 1994 marine. Sailing heritage."),
m("Mexx","Woman EDP","female",2004,3.52,["spring","fall"],["floral","fresh","fruity","musk"],"Mexx woman. Fresh accessible. Urban casual."),
m("Calvin Klein","Summer EDP","female",2008,3.62,["spring","summer"],["fresh","floral","fruity","citrus"],"Summer CK. Light and sunny. Season freshness."),
m("Calvin Klein","CK Free EDT","male",2009,3.62,["spring","fall"],["fresh","herbal","woody","citrus"],"CK Free. Juniper and amber. Free masculinity."),
m("Ralph Lauren","Purple Label EDP","male",2012,3.88,["fall","winter"],["woody","aromatic","spicy","amber"],"Purple label luxury. Cedar and spices. Refined."),
m("Ralph Lauren","Romance Men EDT","male",2002,3.75,["spring","fall"],["aromatic","fresh","woody","citrus"],"Romance masculine. Coriander and cedar. Gentleman."),
m("Marc Jacobs","Bang Bang EDT","male",2014,3.62,["spring","fall"],["fresh","woody","citrus","aromatic"],"Bang masculine. Pepper and cedar. Urban cool."),
m("Givenchy","Hot Couture EDP","female",2000,3.72,["spring","fall"],["floral","sweet","woody","musk"],"Hot couture. Magnolia and iris. Fashion elegance."),
m("Givenchy","Play Intense EDP","male",2010,3.72,["fall","winter"],["woody","spicy","citrus","amber"],"Play intense. Hazelnut and pepper. Bold version."),
m("Lancôme","Magnifique EDP","female",2008,3.72,["spring","fall"],["floral","fruity","woody","musk"],"Magnifique. Rose and magnolia. French radiance."),
m("Lancôme","Poeme EDP","female",1995,3.92,["fall","winter"],["floral","sweet","vanilla","oriental"],"A poem. Magnolia and mimosa. Opulent 90s classic."),
m("Lancôme","Mille et Une Roses EDP","female",2013,3.85,["spring","fall"],["rose","floral","powdery","musk"],"Thousand roses. Rose and iris. Garden luxury."),
m("Paco Rabanne","Pure XS Night EDP","female",2018,3.82,["fall","winter"],["sweet","floral","amber","musk"],"Pure XS night. Vanilla and flowers. Night luxury."),
m("Paco Rabanne","Lady Million Fabulous EDP","female",2021,3.92,["fall","winter"],["floral","sweet","amber","vanilla"],"Fabulous million. Jasmine and vanilla. Opulent."),
m("Jean Paul Gaultier","Classique EDP","female",2002,4.02,["spring","fall"],["floral","oriental","powdery","sweet"],"Classique EDP. More intense corseted. Opulent feminine."),
m("Jean Paul Gaultier","Scandal pour Homme EDT","male",2021,3.78,["fall","winter"],["warm spicy","tobacco","sweet","citrus"],"Scandal him. Tobacco and vanilla. Confident charming."),
// Niche extras
m("Byredo","Lil Fleur EDP","unisex",2021,3.95,["spring","fall"],["floral","fruity","fresh","musk"],"Little flower. Rose and yuzu. Small luxury."),
m("Byredo","Mixed Emotions EDP","unisex",2022,4.18,["fall","winter"],["floral","woody","musk","spicy"],"Mixed emotions. Cardamom and orris. Emotional luxury."),
m("Byredo","Accord Oud EDP","unisex",2012,4.15,["fall","winter"],["oud","floral","spicy","amber"],"Oud accord. Rose and saffron. Swedish meets Arabia."),
m("Byredo","Manifest EDP","unisex",2021,4.12,["fall","winter"],["amber","woody","floral","musk"],"Manifest. Iris and amber. Future luxury."),
m("Maison Margiela","Replica Coffee Break EDT","unisex",2017,3.98,["fall","winter"],["coffee","sweet","creamy","woody"],"Morning coffee break. Cardamom and creamy coffee. Comfort."),
m("Maison Margiela","Replica On A Date EDT","unisex",2020,3.88,["spring","fall"],["iris","floral","powdery","fresh"],"First date nerves. Iris and rose. Romantic hopeful."),
m("Maison Margiela","Replica Under the Lemon Trees EDT","unisex",2020,3.82,["spring","summer"],["citrus","floral","fresh","tea"],"Under lemon tree. Neroli and lemon. Mediterranean happiness."),
m("Jo Malone London","Vetiver and Golden Vanilla CI","unisex",2017,4.12,["fall","winter"],["vetiver","vanilla","amber","sweet"],"Smoky vanilla. Vetiver and golden vanilla. Warm luxury."),
m("Jo Malone London","Tuberose and Angelica CI","female",2012,4.18,["spring","fall"],["white floral","floral","musk","woody"],"Intense tuberose. Angelica and musk. Ultimate tuberose."),
m("Jo Malone London","Velvet Rose and Oud CI","unisex",2012,4.15,["fall","winter"],["rose","oud","woody","spicy"],"Jo Malone intense. Turkish rose and oud. Rich luxury."),
m("Diptyque","Florabellio EDT","unisex",2013,3.88,["spring","summer"],["floral","fresh","green","woody"],"Coffee blossom paradise. Apple and jasmine. Surprising."),
m("Diptyque","Eau des Sens EDT","unisex",2018,3.92,["spring","summer"],["fresh","woody","citrus","spicy"],"Nature walked through. Orange and juniper. Botanical."),
m("Diptyque","Ofresia EDT","unisex",2010,3.85,["spring","summer"],["floral","fruity","fresh","musk"],"Freesia and peach. Delicate and joyful. Light spring."),
m("Acqua di Parma","Colonia Intensa EDP","male",2010,4.15,["fall","winter"],["citrus","aromatic","amber","woody"],"Intense Colonia. Deeper resinous. Dressed elegance."),
m("Acqua di Parma","Assoluta di Colonia EDT","unisex",2012,3.95,["spring","summer"],["citrus","floral","woody","aromatic"],"Summer absolute. Lightest Colonia. Pure Italian."),
m("Penhaligon's","Endymion Cologne","male",2004,4.02,["spring","fall"],["aromatic","citrus","lavender","woody"],"English garden. Lavender and cardamom. Quintessentially British."),
m("Penhaligon's","Juniper Sling EDT","male",2010,3.98,["spring","summer","fall"],["aromatic","citrus","fresh","woody"],"Gin and Tonic inspired. Juniper and botanicals. Refreshing."),
m("Roja Dove","Elysium Pour Homme EDP","male",2017,4.42,["fall","winter"],["fresh","citrus","woody","aromatic"],"Accessible Roja masterpiece. Fresh and woody harmony."),
m("Initio Parfums Privés","Paragon EDP","unisex",2020,4.18,["fall","winter"],["musk","spicy","woody","aromatic"],"Paragon of beauty. Ambrette and iso E super. Clean power."),
m("Initio Parfums Privés","Atomic Rose EDP","female",2020,4.12,["spring","fall"],["rose","musk","floral","sweet"],"Atomic rose. Ambrette and magnolia. Rose reinvented."),
m("Tiziana Terenzi","Bianco Puro EDP","unisex",2018,4.08,["spring","summer"],["musk","white floral","fresh","iris"],"Pure white. Clean musk and iris. Italian purity."),
m("Nishane","Papilefiko EDP","unisex",2018,4.08,["spring","summer"],["fruity","floral","fresh","musk"],"Butterfly effect. Mandarin and flowers. Delicate."),
m("Xerjoff","Accademia EDP","unisex",2015,4.12,["fall","winter"],["amber","woody","warm spicy","resinous"],"Italian craftsmanship. Resinous woods and spices. Collectible."),
m("Xerjoff","Aqua Regia EDP","unisex",2018,4.02,["spring","summer"],["citrus","floral","fresh","musk"],"Noble water. Citrus and jasmine. Summer Italian luxury."),
m("Kilian","Roses on Ice EDP","unisex",2014,4.15,["spring","fall"],["rose","violet","rhubarb","musk"],"Roses on ice. Rhubarb and rose. Crisp floral luxury."),
m("Kilian","Amor Fati EDP","unisex",2013,4.08,["fall","winter"],["floral","sandalwood","musk","amber"],"Love of fate. Sandalwood and flowers. Stoic luxury."),
m("Le Labo","Mousse de Chene 30 EDP","unisex",2020,4.22,["fall","winter"],["mossy","woody","iris","earthy"],"Forest floor luxury. Oakmoss and iris. Quiet contemplative."),
m("Le Labo","Vetiver 46 EDP","unisex",2006,4.18,["spring","fall"],["vetiver","woody","citrus","earthy"],"Vetiver 46. Gaiac and cedar. The vetiver reference."),
m("Serge Lutens","Nuit de Cellophane EDP","female",2009,3.95,["spring","fall"],["white floral","floral","fresh","musk"],"Cellophane night. Peony and freesia. Light fresh."),
m("Serge Lutens","Vêtiver Oriental EDP","unisex",2004,4.12,["fall","winter"],["vetiver","oriental","floral","amber"],"Oriental vetiver. Rose and amber. East meets vetiver."),
m("Frederic Malle","Synthetic Jungle EDP","unisex",2019,4.12,["spring","fall"],["green","woody","earthy","fresh"],"Synthetic jungle. Guaiac and vetiveryl. Urban nature."),
// Middle East extras
m("Lattafa","Ana Abiyedh EDP","female",2020,3.98,["fall","winter"],["floral","musk","rose","sweet"],"I am white. Rose and musk. Pure Arabic feminine."),
m("Lattafa","Tamuh EDP","unisex",2020,4.08,["fall","winter"],["oud","amber","spicy","floral"],"Ambition. Oud and black pepper. Strong confident."),
m("Rasasi","Nafaeis Al Shaghaf EDP","unisex",2018,4.0,["fall","winter"],["oud","floral","spicy","amber"],"Precious love. Rose and saffron oud. Pure Arabic."),
m("Afnan","Ornament EDP","unisex",2020,3.88,["fall","winter"],["oud","amber","floral","sweet"],"Ornament. Oud and rose amber. Decorated luxury."),
m("Swiss Arabian","Amaali EDP","unisex",2020,4.08,["fall","winter"],["oud","rose","sweet","amber"],"Hope. Rose and oud. Arabian aspiration."),
m("Swiss Arabian","Oud 24 Hours EDP","unisex",2018,4.15,["fall","winter"],["oud","amber","woody","sweet"],"24-hour oud. Pure and long-lasting. True dedication."),
m("Arabian Oud","Bakhoor Oud EDP","unisex",2019,4.15,["fall","winter"],["oud","incense","amber","resinous"],"Bakhour oud. Incense and oud. Traditional ritual."),
m("Arabian Oud","Mukhallat Malaki EDP","unisex",2015,4.15,["fall","winter"],["oud","rose","incense","amber"],"Royal blend. Oud and incense. Regal Arabian luxury."),
m("Zimaya","Ameer Al Oud Special EDP","unisex",2018,4.18,["fall","winter"],["oud","spicy","amber","sweet"],"Prince of oud. Saffron and pure oud. Royal statement."),
m("Zimaya","Hawaa EDP","female",2019,4.12,["spring","fall"],["floral","fruity","sweet","amber"],"Garden of Eve. Rose and peach. Sweet Eastern femininity."),
m("Maison Alhambra","Hekayati EDP","female",2022,4.02,["spring","fall"],["floral","fruity","sweet","rose"],"My story. Raspberry and rose. Affordable Eastern."),
m("Paris Corner","Pendora Scent Gold EDP","unisex",2022,3.98,["fall","winter"],["amber","oud","sweet","spicy"],"Gold pendora. Amber and oud. Opulent Eastern."),
m("Armaf","Niche Italiano EDP","unisex",2020,3.88,["fall","winter"],["floral","musk","woody","iris"],"Niche italiano. Clean and refined. Premium Armaf."),
// Zara extras
m("Zara","Downtown Girl EDP","female",2021,3.72,["spring","fall"],["floral","fresh","musk","citrus"],"Downtown girl. Urban feminine. Zara street style."),
m("Zara","Denim Couture EDT","unisex",2021,3.68,["spring","fall"],["fresh","woody","musk","aromatic"],"Denim couture. Clean and casual. Affordable chic."),
m("Zara","Freesia EDP","female",2022,3.70,["spring","summer"],["floral","fresh","white floral","musk"],"Zara freesia. Light and accessible. Garden fresh."),
m("Zara","Gardenia EDP","female",2021,3.68,["spring","summer"],["white floral","floral","fresh","musk"],"Zara gardenia. White flower. Accessible garden."),
m("Zara","Seoul EDP","unisex",2021,3.78,["spring","fall"],["floral","fruity","fresh","musk"],"Seoul vibes. Apple and rose. Korean-inspired freshness."),
m("Zara","Man Gold EDP","male",2022,3.82,["fall","winter"],["amber","woody","spicy","aromatic"],"Zara gold masculine. Cardamom and amber. Warm."),
m("Zara","Tobacco Collection Brown EDP","unisex",2021,3.80,["fall","winter"],["tobacco","woody","amber","spicy"],"Tobacco Zara. Oud and tobacco. Niche inspired."),
// Kayali extras
m("Kayali","Elixir 11 EDP","unisex",2022,4.02,["fall","winter"],["oriental","amber","floral","sweet"],"Elixir 11. Rose and amber. Premium accessible."),
m("Kayali","Vanilla 28 EDP","unisex",2019,4.05,["fall","winter"],["vanilla","floral","sweet","oriental"],"Vanilla 28. Cardamom and rose vanilla. Sweet luxury."),
// Dossier extras
m("Dossier","Oriental Myrrh EDP","unisex",2022,3.75,["fall","winter"],["resinous","oriental","amber","incense"],"Myrrh orient. Incense and amber. Affordable resin."),
m("Dossier","Floral Neroli EDP","female",2021,3.75,["spring","summer"],["citrus","white floral","fresh","musk"],"Accessible neroli. Orange blossom and jasmine. Clean."),
// Bath Body extras
m("Bath & Body Works","Bare Vanilla EDP","female",2022,3.68,["spring","fall"],["vanilla","musk","woody","sweet"],"Bare vanilla. Skin and vanilla. Transparent luxury."),
// Victoria extras
m("Victoria's Secret","Dream Angels Heavenly EDP","female",2016,3.70,["spring","fall"],["floral","musk","sweet","fresh"],"Dream angel. White peony and musk. Ethereal."),
m("Victoria's Secret","Very Sexy Now EDT","female",2003,3.58,["spring","summer"],["floral","fruity","fresh","musk"],"Very sexy now. Fresh and flirtatious. VS signature."),
// Elizabeth Arden extras
m("Elizabeth Arden","Splendor EDP","female",1998,3.72,["spring","summer"],["floral","fresh","aldehydic","woody"],"Splendid bright. Peony and iris. Classic radiance."),
m("Elizabeth Arden","True Love EDT","female",1994,3.68,["spring","summer"],["floral","iris","fresh","woody"],"True love floral. Iris and rose. Timeless feminine."),
m("Elizabeth Arden","Fantasy Emerald Dreams EDP","female",2017,3.58,["spring","summer"],["floral","fruity","fresh","musk"],"Emerald dreams. Apple and jasmine. Fresh dreamy."),
// Estée Lauder extras
m("Estée Lauder","Beautiful Sheer EDP","female",2001,3.72,["spring","summer"],["floral","fresh","sheer","musk"],"Beautiful sheer. Lighter Beautiful. Daytime version."),
m("Estée Lauder","Dazzling Silver EDP","female",2001,3.65,["spring","fall"],["floral","fresh","citrus","musk"],"Dazzling silver. Bright and clean. Radiant."),
m("Estée Lauder","Azuree EDP","female",1969,3.88,["spring","summer"],["chypre","floral","green","citrus"],"Azure. Green chypre. 1969 summer classic."),
// Donna extras
m("Donna Karan","Pure DKNY EDP","female",2010,3.68,["spring","fall"],["floral","musk","fresh","woody"],"Pure DKNY. Clean and natural. Urban nature."),
m("Donna Karan","DKNY Energizing EDP","female",2009,3.62,["spring","summer"],["fresh","floral","fruity","musk"],"Energizing DKNY. Fresh and vibrant. Urban energy."),
// Heritage extras
m("Jean Patou","1000 EDP","female",1972,4.05,["fall","winter"],["chypre","floral","earthy","aldehydic"],"A thousand. Chypre floral. 1972 power."),
m("Lenthéric","Tweed EDP","female",1933,3.88,["fall","winter"],["chypre","floral","earthy","aldehydic"],"British tweed. Rose and oakmoss. 1933 heritage."),
m("Dana","Tabu EDP","female",1932,3.82,["fall","winter"],["oriental","floral","spicy","earthy"],"Notorious 1932. Spiced oriental with civet. Scandalous."),
m("Houbigant","Fougere Royale EDT","male",1882,4.08,["fall","winter"],["fougere","lavender","oakmoss","coumarin"],"The first fougere. 1882. Lavender and oakmoss. The original."),
m("Roger Vivier","Je T'Aime EDP","female",2019,3.88,["spring","fall"],["floral","rose","soft","musk"],"I love you. Rose and sandalwood. Shoe luxury."),
m("Shiseido","Zen EDP","female",1964,3.88,["fall","winter"],["floral","oriental","amber","woody"],"Zen harmony. Rose and sandalwood. Japanese meditative."),
m("Czech Czech","Black Nuit de Bakelite EDT","unisex",2011,3.88,["fall","winter"],["floral","aldehydic","smoky","woody"],"Bakelite nights. Tuberose and smoke. Czech artistry."),
// Remaining celebrity
m("Kim Kardashian","KKW Crystal Gardenia EDP","female",2017,3.65,["spring","fall"],["floral","gardenia","musk","clean"],"Crystal gardenia. White gardenia. Transparency."),
m("Selena Gomez","New Signature EDP","female",2022,3.72,["spring","fall"],["floral","fruity","vanilla","musk"],"Selena's signature. Floral and vanilla. Pop princess."),
m("Jay-Z","Gold EDP","male",2013,3.55,["fall","winter"],["fresh","citrus","woody","amber"],"Jay-Z gold. Fresh and accessible. Hip-hop luxury."),
m("Usher","He EDP","male",2007,3.52,["spring","fall"],["fresh","spicy","woody","amber"],"Usher he. Fresh and dynamic. R&B masculine."),
m("50 Cent","Power EDP","male",2010,3.45,["fall","winter"],["woody","amber","spicy","citrus"],"Power. Bold and accessible. Hip-hop."),
m("Sarah Jessica Parker","SJP Stash EDP","unisex",2015,3.68,["fall","winter"],["woody","amber","tobacco","spicy"],"Stash. Tobacco and cedar. Private collection."),
m("Jennifer Lopez","Promise EDP","female",2021,3.62,["spring","fall"],["floral","fruity","sweet","musk"],"Promise J.Lo. Cashmere and floral. Continued legacy."),
m("Taylor Swift","Glitter Wonderstruck EDT","female",2012,3.62,["spring","fall"],["floral","fruity","sweet","musk"],"Glitter wonder. Hibiscus and musk. Sparkle everywhere."),
m("Justin Bieber","Santa EDP","male",2012,3.55,["fall","winter"],["warm spicy","sweet","vanilla","woody"],"Santa Bieber. Cinnamon and vanilla. Holiday scent."),
m("One Direction","Between Us EDP","female",2013,3.55,["spring","fall"],["floral","fruity","fresh","musk"],"Between us. Mandarin and peach. Pop band feminine."),
// Sport brand extras
m("Adidas","Moves for Her EDT","female",2007,3.45,["spring","summer"],["fresh","floral","citrus","musk"],"Feminine moves. Mandarin and jasmine. Active light."),
m("Nike","Sport EDT","male",2010,3.48,["spring","summer"],["fresh","aquatic","citrus","musk"],"Nike sport v2. Athletic freshness. Just do it."),
m("Puma","Blue Generation EDT","male",2009,3.48,["spring","summer"],["aquatic","fresh","citrus","musk"],"Blue generation. Sea and citrus. Sport fresh."),
// Miscellaneous remaining
m("Naomi Campbell","Sunrise EDT","female",2014,3.52,["spring","summer"],["floral","fruity","citrus","musk"],"Sunrise beauty. Mandarin and jasmine. Morning glow."),
m("Nicki Minaj","Queen EDP","female",2019,3.65,["spring","fall"],["floral","fruity","musk","sweet"],"Queen energy. Floral and fruity. Fearless femininity."),
m("Kylie Jenner","Kylie Kylie EDP","female",2022,3.60,["spring","fall"],["floral","fruity","vanilla","musk"],"Kylie signature. Rose and vanilla. Lip kit scent."),
m("Hilary Duff","With Love EDP","female",2006,3.50,["spring","summer"],["floral","fruity","sweet","musk"],"With love. Magnolia and musk. Pop princess."),
m("Ed Hardy","Born Wild EDP","female",2011,3.55,["spring","fall"],["floral","fruity","sweet","musk"],"Born wild. Strawberry and jasmine. Tattoo art."),
m("Antonio Banderas","Queen of Seduction EDP","female",2012,3.55,["spring","fall"],["floral","fruity","sweet","musk"],"Queen seduction. Peach and rose. Latin."),
m("Beckham","Intimately Yours Men EDT","male",2009,3.58,["spring","fall"],["fresh","aromatic","woody","citrus"],"Intimately yours. Fresh and sporty. David's gift."),
m("Sean John","I Am King EDP","male",2009,3.62,["fall","winter"],["fresh","woody","amber","citrus"],"I am king. Bergamot and vetiver. Royal masculine."),
m("Mariah Carey","Lollipop Bling EDP","female",2008,3.55,["spring","summer"],["fruity","floral","sweet","musk"],"Lollipop bling. Cherry and vanilla. Sweet pop."),
m("American Eagle","Ne01 EDP","female",2013,3.55,["spring","summer"],["floral","fresh","fruity","musk"],"AE Ne01. Fresh and natural. American clean."),
m("Hollister","Pulse EDT","female",2013,3.58,["spring","summer"],["floral","fresh","fruity","musk"],"Pulse SoCal. Fresh and light. California girl."),
m("Bench","Body for Men EDT","male",2009,3.50,["spring","summer"],["fresh","citrus","woody","musk"],"Bench body. Fresh and casual. Everyday accessible."),
m("Replay","Stone for Him EDT","male",2009,3.52,["spring","fall"],["fresh","woody","citrus","aromatic"],"Replay stone. Fresh and solid. Casual accessible."),
m("Gap","Heaven EDT","female",2001,3.52,["spring","summer"],["floral","fresh","citrus","musk"],"Heavenly Gap. Simple and clean. Accessible beauty."),
m("Gap","So Pink EDT","female",2012,3.48,["spring","summer"],["floral","fruity","fresh","musk"],"So pink. Light and playful. Casual freshness."),
// Complete the remaining niche
m("Parfums Quartana","Rose Satin EDP","female",2019,3.92,["spring","fall"],["rose","woody","spicy","floral"],"Satin rose. Cardamom and jasmine. Modern luxury rose."),
m("Henry Rose","Jake EDP","unisex",2020,3.82,["spring","fall"],["fresh","woody","citrus","aromatic"],"Jake. Fresh woods. Sustainable masculine."),
m("Malin + Goetz","Blood Orange EDT","unisex",2015,3.78,["spring","summer"],["citrus","fresh","aromatic","musk"],"Blood orange artisan. Bright citrus. Brooklyn joy."),
m("Commodity","Whiskey EDP","male",2016,3.88,["fall","winter"],["tobacco","woody","spicy","amber"],"Whiskey barrel. Tobacco and cedar. Artisan masculine."),
m("D.S. & Durga","Radio Bombay EDP","unisex",2016,3.98,["spring","fall"],["spicy","rose","oud","amber"],"Radio waves from Bombay. Saffron and cardamom. Cultural fusion."),
m("Imaginary Authors","Cobra and Canary EDP","unisex",2012,3.85,["spring","summer"],["floral","fruity","green","musk"],"Colorful snake story. Grapefruit and gardenia. Whimsical."),
m("Boy Smells","Tantrum EDP","unisex",2018,3.85,["spring","fall"],["floral","fruity","musk","fresh"],"Tantrum. Peach and musk. Playful premium."),
m("Zoologist Perfumes","Hummingbird EDP","unisex",2019,3.98,["spring","summer"],["tropical","floral","coconut","fresh"],"Tropical nectar. Jasmine and coconut. Exotic garden."),
m("CLEAN Beauty","Reserve Rain EDP","unisex",2015,3.75,["spring","summer"],["aquatic","fresh","musk","clean"],"Clean rain. Aquatic and musk. Transparent freshness."),
m("Memo Paris","Wild Geranium EDP","female",2015,3.95,["spring","fall"],["floral","rose","fresh","woody"],"Wild geranium. Rose and jasmine. Natural vibrant."),
m("Etro","Heliotrope EDP","unisex",2004,3.92,["spring","fall"],["floral","powdery","sweet","almond"],"Heliotrope and almond. Powdery comforting. Intellectual."),
m("Ex Nihilo","Fleur Narcotique EDP","unisex",2013,4.22,["spring","fall"],["white floral","floral","spicy","creamy"],"Narcotic flowers. Tuberose and jasmine. Addictive luxury."),
m("Profumum Roma","Acqua di Sale EDP","unisex",2001,4.22,["spring","summer"],["aquatic","marine","fresh","musk"],"Sea salt luxury. Roman maritime spirit. Ocean."),
m("Liquides Imaginaires","Peau de Bete EDP","unisex",2012,4.15,["fall","winter"],["leather","animalic","musk","amber"],"Beast skin. Raw leather and musk. Provocative."),
m("The Different Company","Rose Poivree EDP","unisex",2000,4.12,["spring","fall"],["rose","spicy","floral","woody"],"Peppered rose. Pink pepper and rose. French niche."),
m("Comptoir Sud Pacifique","Motu Koloa EDT","unisex",2014,3.78,["spring","summer"],["floral","tropical","coconut","sweet"],"Pacific island. Tiare and coconut vanilla. Dreamy escape."),
m("Profumum Roma","Dolce Acqua EDP","unisex",2009,3.98,["spring","summer"],["citrus","white floral","fresh","musk"],"Sweet water. Neroli and white flowers. Italian freshness."),
m("Floris","White Rose EDP","female",1911,3.95,["spring","summer"],["floral","white floral","fresh","powdery"],"White rose 1911. Delicate English. Heritage simplicity."),
m("Reminiscence","Patchouli EDP","unisex",1970,3.98,["fall","winter"],["patchouli","earthy","woody","musk"],"Pure patchouli since 1970. The hippie heritage."),
m("Reminiscence","Vanille EDP","unisex",1993,3.75,["fall","winter"],["vanilla","sweet","floral","musk"],"Pure vanilla warmth. Jasmine and vanilla. Simple comfort."),
m("L'Occitane","Fleurs de Cerisier EDP","female",2014,3.65,["spring","summer"],["floral","cherry","fresh","musk"],"Cherry blossoms. Light and airy. Japanese inspired."),
m("Roger & Gallet","Bois d'Orange EDT","unisex",2013,3.68,["spring","fall"],["citrus","woody","aromatic","fresh"],"Orange wood. Bergamot and cedarwood. Clean fresh."),
];

const existing=JSON.parse(readFileSync(DATA,"utf-8"));
console.log(`Mevcut: ${existing.length}`);
const seen=new Map(existing.map(p=>[`${p.brand}|${p.name}`.toLowerCase().trim(),true]));
let added=0;const merged=[...existing];
for(const p of N){
  const key=`${p.brand}|${p.name}`.toLowerCase().trim();
  if(!seen.has(key)){seen.set(key,true);merged.push(p);added++;}
}
merged.forEach((p,i)=>{p.id=String(i+1);});
writeFileSync(DATA,JSON.stringify(merged,null,2),"utf-8");
console.log(`Eklenen: ${added}`);
console.log(`Toplam: ${merged.length}`);
