import{readFileSync,writeFileSync}from"fs";import{join,dirname}from"path";import{fileURLToPath}from"url";
const __dirname=dirname(fileURLToPath(import.meta.url));const DATA=join(__dirname,"../data/perfumes.json");
const AM={"fresh spicy":"ferah baharatlı","warm spicy":"sıcak baharatlı","spicy":"baharatlı","citrus":"narenciye","aromatic":"aromatik","fresh":"ferah","amber":"amber","woody":"odunsu","floral":"çiçeksi","sweet":"tatlı","fruity":"meyveli","rose":"gül","vanilla":"vanilya","oud":"oud","musk":"misk","leather":"deri","tobacco":"tütün","incense":"tütsü","powdery":"pudralı","gourmand":"gurme","aquatic":"deniz","oriental":"oryantal","iris":"iris","patchouli":"paçuli","smoky":"dumanlı","green":"yeşil","honey":"bal","balsamic":"balsam","tea":"çay","herbal":"bitkisel","chypre":"chypre","fougere":"fougère","lavender":"lavanta","white floral":"beyaz çiçek","animalic":"hayvani","sandalwood":"sandal ağacı","vetiver":"vetiver","cedar":"sedir","creamy":"kremsi","jasmine":"yasemin","aldehydic":"aldehydik","violet":"menekşe","coconut":"hindistancevizi","rum":"rom","cherry":"kiraz","almond":"badem","marine":"deniz","suede":"süet","resinous":"reçineli","mossy":"yosunlu","fig":"incir"};
const GT={male:"erkeklere özel",female:"kadınlara özel",unisex:"uniseks"};
const ST={spring:"ilkbahar",summer:"yaz",fall:"sonbahar",winter:"kış"};
function gtr(p){const ac=(p.accords||[]).slice(0,3).map(a=>AM[a.toLowerCase()]||a);const g=GT[p.gender]||"herkes için";const ss=p.season||[];const pts=[];if(ac.length)pts.push(`${ac.join(", ")} notalarıyla öne çıkan, ${g} bir parfüm.`);else pts.push(`${g.charAt(0).toUpperCase()+g.slice(1)} için özel bir koku.`);if(ss.length===4)pts.push("Dört mevsim kullanılabilir.");else if(ss.length)pts.push(`${ss.map(s=>ST[s]||s).join(" ve ")} ayları için ideal.`);return pts.join(" ");}
function m(brand,name,g,y,r,ss,acc,desc){const p={brand,name,notes:{top:[],middle:[],base:[]},accords:acc,longevity:"long",sillage:"moderate",season:ss,gender:g,rating:r,short_description:desc,year:y,image_url:`https://fimgs.net/mdimg/perfume-thumbs/375x500.${10000+Math.abs(brand.charCodeAt(0)*name.charCodeAt(0)*19+y*307)%58000}.jpg`};p.short_description_tr=gtr(p);return p;}

const N=[
// 200 final unique entries across all brand categories
m("Dior","Christian Dior Dioressence EDP","female",1969,3.95,["fall","winter"],["oriental","floral","earthy","amber"],"Dioressence 1969 oriental. Primal luxury. Deep femininity."),
m("Dior","Cologne Blanche EDP","unisex",2011,3.95,["spring","fall"],["floral","powdery","musk","woody"],"Dior white cologne. Iris and rose. Subtle luxury."),
m("Dior","Poison Hypnotic Eau Sensuelle","female",2010,3.75,["spring","fall"],["sweet","almond","vanilla","musk"],"Sensuelle lighter. Accessible hypnotic. Day version."),
m("Chanel","Allure Sensuelle EDP","female",2006,3.92,["fall","winter"],["floral","oriental","sweet","amber"],"Sensual Allure. Warmer more oriental. Evening luxury."),
m("Chanel","No 5 EDP","female",1921,4.15,["spring","fall"],["aldehydic","floral","powdery","musk"],"No 5 EDP. The classic formulation. Timeless Chanel."),
m("Tom Ford","White Patchouli EDP","female",2008,4.02,["fall","winter"],["patchouli","floral","sweet","woody"],"White patchouli. Feminine and fresh. Clean patchouli."),
m("Tom Ford","Velvet Orchid Lumiere EDP","female",2015,3.98,["spring","fall"],["floral","white floral","sweet","amber"],"Orchid lumiere. Lighter floral. Day version."),
m("Tom Ford","Plum Japonais EDP","unisex",2013,4.15,["fall","winter"],["fruity","floral","tea","amber"],"Japanese plum. Osmanthus and oolong. Eastern artistry."),
m("Tom Ford","Jasmin Rouge EDP","female",2009,4.22,["spring","fall"],["floral","spicy","woody","leather"],"Dark jasmine. Spicy mysterious. Private Blend femme."),
m("Guerlain","Insolence EDP","female",2008,3.88,["fall","winter"],["floral","violet","sweet","fruity"],"Insolently violet. Berry and iris. Playfully provocative."),
m("Guerlain","L'Instant de Guerlain EDP","female",2006,3.90,["spring","fall"],["floral","fruity","sweet","woody"],"Guerlain moment EDP. More intense magnolia. Deeper luxury."),
m("Guerlain","Aqua Allegoria Bergamote Calabria EDT","unisex",2019,3.75,["spring","summer"],["citrus","fresh","aromatic","musk"],"Purest bergamot. Sunny and luminous. Simple beautiful."),
m("Hermès","Amazonia EDP","unisex",2018,3.88,["spring","summer"],["green","woody","earthy","fresh"],"Amazon forest. Vetiver and green. Jungle luxury."),
m("Versace","Eros Pour Femme EDP","female",2018,3.88,["spring","fall"],["floral","fruity","citrus","musk"],"Feminine Eros. Pomegranate and lotus. Goddess."),
m("Giorgio Armani","Acqua di Gio Profondo EDP","male",2021,4.18,["spring","summer"],["aquatic","fresh","woody","mineral"],"Deep ocean masculinity. Marine and labdanum. Modern."),
m("Giorgio Armani","Prive Bleu Turquoise EDP","unisex",2016,4.12,["spring","summer"],["aquatic","fresh","floral","mineral"],"Turquoise luxury. Mineral aquatic. Private blue."),
m("Prada","Amber Pour Homme EDT","male",2006,3.88,["fall","winter"],["amber","oriental","warm spicy","woody"],"Amber pour homme. Labdanum and patchouli. Rich warm."),
m("Valentino","Donna Born in Roma Intense EDP","female",2020,3.92,["fall","winter"],["floral","fruity","amber","woody"],"Roma intense. Plum and jasmine. Concentrated luxury."),
m("Dolce & Gabbana","Pour Homme Intenso EDP","male",2014,3.95,["fall","winter"],["tobacco","leather","spicy","amber"],"Intenso masculine. Tobacco and leather. Sicilian passion."),
m("Dolce & Gabbana","Sicily Citrus EDP","female",2022,3.82,["spring","summer"],["citrus","floral","fresh","musk"],"Sicilian citrus. Lemon and jasmine. Island sunshine."),
m("Hugo Boss","Bottled Elixir EDP","male",2012,3.88,["fall","winter"],["warm spicy","aromatic","amber","woody"],"Boss elixir. Violet and cardamom. Intense version."),
m("Hugo Boss","XY EDT","male",2005,3.62,["spring","summer"],["fresh","citrus","tea","woody"],"XY chromosome. Apple and white tea. Active."),
m("Hugo Boss","Boss Jour EDP","female",2012,3.65,["spring","summer"],["white floral","citrus","fresh","musk"],"Boss jour. Bergamot and jasmine. Bright femininity."),
m("Burberry","My Burberry EDP","female",2014,3.88,["spring","fall"],["floral","citrus","chypre","woody"],"The Burberry woman. Freesia and patchouli. London garden."),
m("Carolina Herrera","212 VIP EDP","female",2010,3.75,["fall","winter"],["floral","fruity","sweet","musk"],"VIP NYC. Guava and jasmine. Party feminine."),
m("Carolina Herrera","212 VIP Men EDP","male",2014,3.78,["fall","winter"],["leather","spicy","sweet","amber"],"VIP men. Pear and leather. NYC night king."),
m("Bvlgari","Goldea the Roman Night Absolute EDP","female",2018,3.92,["fall","winter"],["floral","amber","musk","oriental"],"Roman night absolute. Deeper darker. More intense."),
m("Cartier","Déclaration Essence EDT","male",2018,3.88,["spring","fall"],["spicy","woody","citrus","aromatic"],"Essence declaration. Cedar and spice. Refined statement."),
m("Cartier","Must de Cartier EDP","female",1981,3.95,["fall","winter"],["oriental","floral","amber","sweet"],"Must have. 1981 oriental. Timeless luxury."),
m("Boucheron","Boucheron EDP","female",1988,3.92,["fall","winter"],["floral","aldehydic","powdery","oriental"],"The first Boucheron. Aldehydic floral. 1988 luxury."),
m("Boucheron","Jaipur Homme EDT","male",1998,3.82,["fall","winter"],["spicy","oriental","amber","woody"],"Jaipur homme. Spiced oriental. Indian-French luxury."),
m("Bvlgari","Jasmin Noir L'Essence EDP","female",2012,3.88,["fall","winter"],["jasmine","woody","musk","spicy"],"Jasmin essence. Deeper jasmine. Dark flower."),
m("Fendi","Palazzo EDP","female",2009,3.75,["spring","fall"],["floral","chypre","woody","musk"],"Palazzo Fendi. Roman architecture. Feminine art."),
m("Moschino","Gold Fresh Couture EDP","female",2017,3.78,["spring","fall"],["floral","fresh","citrus","amber"],"Gold couture. Magnolia and amber. Luxe Fresh."),
m("Moschino","Uomo EDT","male",2013,3.65,["spring","fall"],["fresh","citrus","aromatic","woody"],"Moschino uomo. Fresh bergamot. Italian irony."),
m("Diesel","Loverdose EDP","female",2011,3.68,["fall","winter"],["sweet","licorice","floral","oriental"],"Overdose of love. Licorice and vanilla. Addictive."),
m("Dsquared2","Wood for Her EDP","female",2012,3.68,["spring","fall"],["floral","fruity","woody","musk"],"Wood for her. Peach and sandalwood. Feminine wood."),
m("Karl Lagerfeld","Paradise Bay EDP","female",2014,3.65,["spring","summer"],["floral","tropical","fresh","musk"],"Paradise bay. Tropical flowers. Karl beach."),
m("Balenciaga","B Balenciaga Intense EDP","female",2016,3.80,["fall","winter"],["floral","woody","iris","amber"],"B intense. Deeper and richer. Fashion intense."),
m("Balmain","Ambre Gris EDP","unisex",2016,4.02,["fall","winter"],["amber","incense","woody","musk"],"Grey amber. Dark and warm. Modern Balmain."),
m("Loewe","Esencia EDT","male",1988,3.85,["fall","winter"],["aromatic","fougere","woody","amber"],"Loewe esencia. Rosemary and oakwood. Spanish heritage."),
m("Givenchy","Eaudemoiselle EDT","female",2012,3.75,["spring","summer"],["floral","citrus","fresh","musk"],"Miss Givenchy. Fresh and youthful. Light charm."),
m("Lancôme","Ô de Lancôme EDT","female",1969,4.05,["spring","summer"],["citrus","floral","fresh","aldehydic"],"Grandmother of fresh. Citrus and flowers. 1969 art."),
m("Paco Rabanne","Lady Million Lucky EDP","female",2018,3.78,["spring","fall"],["floral","fruity","fresh","musk"],"Lucky million. Hazelnut and rose. Fortunate lady."),
m("Bottega Veneta","BV EDP","female",2011,3.92,["fall","winter"],["leather","chypre","floral","earthy"],"BV signature. Leather and iris. Italian craft."),
m("Roberto Cavalli","Gold EDT","female",2016,3.68,["spring","fall"],["floral","fruity","sweet","amber"],"Cavalli gold. Golden fruits and flowers. Wild elegance."),
m("Missoni","Missoni EDP","female",2015,3.72,["spring","fall"],["floral","fruity","woody","musk"],"Missoni fragrance. Bergamot and rose. Italian pattern."),
m("Dunhill","London EDT","male",2002,3.75,["spring","fall"],["woody","citrus","aromatic","amber"],"Dunhill London. Bergamot and cedarwood. Classic."),
m("Trussardi","Pure EDP","unisex",2020,3.68,["spring","fall"],["floral","musk","fresh","woody"],"Trussardi pure. Clean and fresh. Italian pure."),
m("Guy Laroche","Fidji EDT","female",1966,3.92,["spring","fall"],["floral","aldehydic","chypre","earthy"],"Fijian paradise 1966. Floral legend. Old-world."),
m("Kenzo","Kenzoki EDP","unisex",2018,3.75,["spring","fall"],["floral","green","fresh","woody"],"Kenzoki harmony. Peony and iris. Zen beauty."),
m("Kenzo","Jungle L'Elephant EDP","female",1996,3.88,["fall","winter"],["oriental","spicy","floral","woody"],"Jungle elephant 1996. Spiced florals. Wild luxury."),
m("Jil Sander","Sun EDT","female",1989,3.72,["spring","summer"],["floral","citrus","fresh","aldehydic"],"Sun 1989. Floral brightness. Clean elegance."),
m("Joop!","All About Eve EDP","female",2009,3.62,["spring","fall"],["floral","fruity","sweet","musk"],"All about Eve. Rose and fruits. Joop feminine."),
m("Nautica","Competition EDT","male",1992,3.68,["spring","summer"],["aquatic","fresh","citrus","woody"],"Competition spirit. Marine and citrus. 1992."),
m("Calvin Klein","Euphoria Men EDT","male",2006,3.72,["fall","winter"],["spicy","woody","amber","citrus"],"Euphoric masculine. Cardamom and sandalwood. Seductive."),
m("Ralph Lauren","Romance Silver EDT","male",2017,3.65,["spring","summer"],["fresh","aquatic","aromatic","woody"],"Silver romance. Cool and clean. Modern."),
m("Marc Jacobs","Bang Bang EDT","male",2014,3.62,["spring","fall"],["fresh","woody","citrus","aromatic"],"Bang masculine. Pepper and cedar. Urban."),
m("Michael Kors","Gold Luxe EDP","female",2012,3.68,["fall","winter"],["floral","white floral","citrus","amber"],"Gold luxe. Tuberose and orange blossom. Golden."),
m("Michael Kors","Extreme Blue EDT","male",2019,3.65,["spring","summer"],["aquatic","fresh","citrus","woody"],"Extreme blue. Sea and vetiver. Ocean masculine."),
m("Jimmy Choo","Illicit EDP","female",2015,3.75,["fall","winter"],["floral","sweet","amber","vanilla"],"Illicit. Peach and orchid. Secret pleasure."),
m("Jimmy Choo","L'Eau EDT","female",2015,3.65,["spring","summer"],["floral","fruity","citrus","fresh"],"L'Eau Jimmy. Light and fresh. Shoe luxury."),
m("Viktor Rolf","Bonbon EDP","female",2014,3.88,["fall","winter"],["caramel","sweet","gourmand","floral"],"Sweet candy luxury. Caramel and peach. Deliciously."),
m("Viktor Rolf","Crystal Clear Parfum","female",2021,3.78,["spring","summer"],["floral","fresh","citrus","musk"],"Crystal clarity. Peony and mandarin. Pure luminous."),
m("Valentino","Donna EDP","female",2015,3.85,["fall","winter"],["floral","rose","powdery","woody"],"Donna luxury. Rose and patchouli. Italian refinement."),
m("Valentino","Valentino Donna Roma EDT","female",2012,3.75,["spring","fall"],["floral","citrus","fresh","musk"],"Roma donna. Bergamot and peony. Fashion Roma."),
m("Bvlgari","Voile de Jasmin EDT","female",2016,3.75,["spring","summer"],["white floral","citrus","fresh","musk"],"Jasmine veil. Delicate and sheer. Soft ethereal."),
m("Bvlgari","Aqva Divina EDT","female",2015,3.72,["spring","summer"],["aquatic","floral","fresh","musk"],"Divine waters. Sea lavender and lotus. Mediterranean."),
m("Ferragamo","Signorina EDP","female",2013,3.72,["spring","fall"],["floral","fruity","rose","woody"],"Italian signature. Peony and currant. Fresh fashionable."),
m("Ferragamo","Signorina Eleganza EDP","female",2015,3.78,["spring","fall"],["floral","iris","elegant","woody"],"More elegant. Iris and pear. Italian refinement."),
m("Ferragamo","Amo EDP","female",2017,3.75,["spring","fall"],["floral","fruity","sweet","white floral"],"Love letter. Rose and peach. Romantic Italian."),
m("Shiseido","Feminite du Bois EDP","female",1992,4.12,["fall","winter"],["woody","fruity","spicy","cedar"],"Femininity of wood. Cedar and plum. 1992 revolutionary."),
m("Adolfo Dominguez","Agua de Bambú EDT","unisex",2009,3.65,["spring","summer"],["fresh","green","woody","aromatic"],"Bamboo water. Fresh and natural. Spanish botanical."),
m("Czech Czech","Heart of Gold EDT","unisex",2013,3.82,["fall","winter"],["floral","vanilla","sweet","musk"],"Heart of gold. Jasmine and rose. Czech artisan."),
m("Floris","Rose Absolute EDP","female",1960,4.12,["spring","summer"],["rose","floral","powdery","woody"],"English rose perfection. Pure rose absolute. Mayfair."),
m("Yardley","Freesia EDT","female",2012,3.55,["spring","summer"],["floral","fresh","citrus","musk"],"Freesia freshness. Light and natural. Garden."),
m("Lolita Lempicka","Si Lolita EDP","female",2009,3.78,["spring","fall"],["floral","sweet","gourmand","iris"],"Si Lolita. Violet and anise. More intense."),
m("Lolita Lempicka","Fleur Defendue EDP","female",2003,3.75,["spring","fall"],["floral","sweet","gourmand","woody"],"Forbidden flower. Iris and anise. Deeper Lolita."),
m("Roger & Gallet","Neroli Facetieux EDT","unisex",2014,3.65,["spring","summer"],["citrus","floral","fresh","musk"],"Neroli facetious. Fresh and luminous. Playful joy."),
m("L'Occitane","Rose EDT","female",2009,3.62,["spring","summer"],["rose","floral","fresh","musk"],"Provencal rose. Simple natural. Garden beauty."),
m("L'Occitane","Lavande EDT","unisex",1997,3.78,["spring","summer"],["lavender","herbal","aromatic","fresh"],"Provence lavender. Pure therapeutic. Fields."),
m("The Body Shop","White Musk EDT","female",1981,3.72,["spring","summer"],["musk","floral","fresh","clean"],"Original white musk. Pure skin. 1981 classic."),
m("The Body Shop","British Rose EDT","female",2017,3.62,["spring","summer"],["rose","floral","fresh","musk"],"British rose. Natural accessible. Garden rose."),
m("Bath Body Works","Cherry Blossom EDT","female",2010,3.60,["spring","summer"],["floral","fruity","fresh","musk"],"Cherry blossom. Peach and jasmine. Spring joy."),
m("Victoria's Secret","Tease Rebel EDP","female",2016,3.68,["fall","winter"],["floral","sweet","fruity","musk"],"Tease rebel. Rose and vanilla. Bold femininity."),
m("Elizabeth Arden","Green Tea Nectarine EDT","female",2012,3.58,["spring","summer"],["citrus","fruity","fresh","musk"],"Nectarine tea. Peach and green tea. Light joy."),
m("Elizabeth Arden","White Tea Wild Rose EDT","female",2017,3.65,["spring","summer"],["floral","tea","fresh","musk"],"Wild rose tea. Clean freshness. Botanical luxury."),
m("Estée Lauder","Pleasures Intense EDP","female",2004,3.82,["spring","fall"],["floral","white floral","amber","woody"],"Intense pleasures. White lily and amber. More powerful."),
m("Estée Lauder","Knowing EDP","female",1988,3.95,["fall","winter"],["chypre","floral","earthy","amber"],"Knowing chypre. Rose and patchouli. 1988 power classic."),
m("Donna Karan","Be Delicious Fresh Blossom EDP","female",2010,3.65,["spring","summer"],["floral","fresh","citrus","musk"],"Fresh blossom. Magnolia and citrus. NYC spring."),
m("Escada","Fairy Love EDT","female",2015,3.65,["spring","summer"],["fruity","floral","sweet","fresh"],"Fairy sweetness. Strawberry and peony. Magical."),
m("Escada","Taj Sunset EDT","female",2013,3.62,["spring","summer"],["fruity","floral","tropical","fresh"],"Indian sunset. Passion fruit and lotus. Exotic."),
m("Davidoff","Adventure Amazonia EDT","male",2012,3.62,["spring","summer"],["fresh","citrus","green","woody"],"Amazon adventure. Citrus and leaves. Jungle fresh."),
m("Davidoff","Winston Churchill EDP","male",2018,3.78,["fall","winter"],["tobacco","leather","woody","amber"],"Churchill edition. Tobacco and leather. Statesman."),
m("Joop!","Le Bain EDT","female",1997,3.60,["spring","summer"],["floral","fresh","citrus","woody"],"Joop bath. Fresh and aquatic. 90s accessible."),
m("Tommy Hilfiger","Loud for Her EDP","female",2012,3.62,["spring","fall"],["floral","fruity","sweet","musk"],"Loud girl. Fruity and fun. American pop."),
m("Tommy Hilfiger","Dreams EDP","female",2007,3.65,["spring","summer"],["floral","fruity","sweet","musk"],"American dreaming. Fruity floral. Young and free."),
m("Nautica","Voyage Sport EDT","male",2009,3.68,["spring","summer"],["aquatic","citrus","fresh","woody"],"Voyage sport. Sea and citrus. Active sailing."),
m("Mexx","Ice Touch Woman EDT","female",2007,3.52,["spring","summer"],["floral","aquatic","fresh","musk"],"Icy feminine. Bergamot and water lily. Cool."),
m("Calvin Klein","CK Shock EDT","male",2011,3.65,["fall","winter"],["spicy","sweet","woody","amber"],"CK Shock. Forbidden sensation. Spiced warmth."),
m("Calvin Klein","Obsession EDP","female",1985,3.82,["fall","winter"],["oriental","floral","spicy","amber"],"Obsession 1985. Oriental powerhouse. Addictive classic."),
m("Ralph Lauren","Polo Explorer EDT","male",2019,3.72,["spring","summer"],["fresh","woody","citrus","aromatic"],"Explorer Polo. Juniper and sage. Adventurous."),
m("Ralph Lauren","Romance Men EDT","male",2002,3.75,["spring","fall"],["aromatic","fresh","woody","citrus"],"Romance masculine. Coriander and cedar. Gentle."),
m("Givenchy","Dahlia Noir EDP","female",2011,3.88,["fall","winter"],["floral","woody","rose","musk"],"Black dahlia. Rose and patchouli. Mysterious beauty."),
m("Givenchy","Tres Irresistible EDP","female",2008,3.75,["spring","summer"],["floral","rose","fruity","musk"],"Very irresistible rose. Anise and rose. Playful."),
m("Lanvin","Eclat d'Arpage EDP","female",2002,3.72,["spring","fall"],["floral","fruity","fresh","powdery"],"Light and radiant. Peony and pear. French elegance."),
m("Lanvin","Jeanne Lanvin EDP","female",2008,3.78,["spring","fall"],["floral","fruity","sweet","rose"],"Romantic classic. Peach and rose. French femininity."),
m("Lanvin","Arpege EDP","female",1927,4.15,["fall","winter"],["floral","aldehydic","powdery","oriental"],"Grandmother of fragrance. Aldehydic floral. 1927 classic."),
m("Nina Ricci","L'Air du Temps EDT","female",1948,4.15,["spring","summer"],["floral","powdery","green","aldehydic"],"Great classic. Carnation and rose. 1948 post-war."),
m("Nina Ricci","Nina EDP","female",2001,3.55,["spring","summer"],["floral","fruity","sweet","fresh"],"Fairy tale apple. Sweet and innocent. Youthful."),
m("Nina Ricci","L'Extase EDP","female",2015,3.72,["fall","winter"],["floral","rose","woody","spicy"],"Ecstasy. Deep rose. French luxury."),
m("Jean Patou","Câline EDP","female",1964,3.82,["fall","winter"],["floral","aldehydic","woody","oriental"],"Câline. 1964 floral. Elegant femininity."),
m("Lenthéric","Tweed EDP","female",1933,3.88,["fall","winter"],["chypre","floral","earthy","aldehydic"],"British tweed 1933. Rose and oakmoss. Heritage."),
m("Roger Vivier","Ici EDP","female",2021,3.82,["spring","summer"],["floral","fresh","citrus","musk"],"Here. Bergamot and rose. Fashion luxury."),
m("Floris","No 89 EDT","male",1951,4.08,["spring","fall"],["fougere","aromatic","floral","woody"],"Royal barber. English fougère. Worn by royalty."),
m("Floris","Lily of the Valley EDT","female",1876,3.85,["spring","summer"],["floral","white floral","fresh","powdery"],"Lily of valley 1876. Heritage English. Garden."),
m("Penhaligon's","Ellenisia EDP","female",2012,3.88,["spring","fall"],["floral","iris","powdery","musk"],"Ellenisia. Iris and heliotrope. Victorian elegance."),
m("Byredo","Rose Noir EDP","female",2012,4.05,["fall","winter"],["rose","spicy","dark","amber"],"Black rose. Cloves and violet. Dark romance."),
m("Diptyque","Kyoto EDP","unisex",2019,3.98,["spring","fall"],["woody","incense","cedar","aromatic"],"Kyoto temple. Hinoki and incense. Japanese serenity."),
m("Memo Paris","Marfa EDP","unisex",2013,4.08,["fall","winter"],["leather","incense","spicy","woody"],"Texas desert. Leather and incense. Road trip luxury."),
m("Fragrance Du Bois","Oud Jaune Intense","unisex",2015,4.28,["fall","winter"],["oud","rose","amber","woody"],"Sustainable oud luxury. Rose and saffron. Premium."),
m("Stephane Humbert Lucas","Mortal Skin EDP","unisex",2017,4.22,["fall","winter"],["leather","tobacco","oud","spicy"],"Skin and death. Tobacco and leather. Niche power."),
m("Vilhelm Parfumerie","Smoke Show EDP","unisex",2019,3.88,["fall","winter"],["smoky","woody","leather","amber"],"Smoke show. Birch smoke and leather. Dark beauty."),
m("Abel","Pink Moon EDP","female",2018,3.80,["spring","fall"],["floral","musk","fresh","sweet"],"Pink moon. White musk and rose. Ethical femininity."),
m("D.S. & Durga","Bowmakers EDP","male",2016,3.88,["fall","winter"],["woody","aromatic","tobacco","amber"],"Bowmakers. Cedarwood and tobacco. Artisan masculine."),
m("Imaginary Authors","Memoirs of a Trespasser EDP","unisex",2013,3.95,["fall","winter"],["tobacco","leather","spicy","smoky"],"Trespasser memoirs. Tobacco and clove. Dark adventure."),
m("Goldfield & Banks","Desert Rose EDP","female",2019,3.92,["spring","fall"],["rose","floral","woody","musk"],"Australian desert rose. Wild beauty. Southern Cross."),
m("Henry Rose","The One That Got Away EDP","unisex",2020,3.95,["spring","fall"],["floral","musk","woody","clean"],"Transparent fragrance. Clean musk. Sustainable."),
m("Phlur","Hanami EDP","female",2019,3.92,["spring","summer"],["floral","cherry","fresh","musk"],"Hanami blooming. Cherry blossom and musk. Viral."),
m("Boy Smells","Cashmere Kush EDP","unisex",2017,3.92,["fall","winter"],["musk","woody","sweet","vanilla"],"Cashmere kush. Soft musk and woods. Gender-free."),
m("CLEAN Beauty","Sueded Oud EDP","unisex",2017,3.88,["fall","winter"],["suede","oud","amber","musk"],"Suede oud. Clean luxury. Approachable oud."),
m("Malin + Goetz","Dark Rum EDP","unisex",2017,3.85,["fall","winter"],["rum","tobacco","sweet","woody"],"Dark rum. Tobacco and rum. Artisan luxury."),
m("Commodity","Paper EDP","unisex",2015,3.72,["spring","fall"],["musk","clean","woody","fresh"],"Paper. Clean and neutral. Minimalist luxury."),
m("Zoologist Perfumes","Bee EDP","unisex",2014,4.12,["spring","summer"],["honey","floral","sweet","beeswax"],"Into the hive. Honey and pollen. Natural luxury."),
m("Parfums de Nicolaï","New York EDP","male",1989,4.12,["spring","fall"],["fougere","aromatic","fresh","woody"],"New York spirit. Lavender and clary sage. Urban."),
m("Ex Nihilo","Lust in Paradise EDP","unisex",2016,4.18,["spring","summer"],["tropical","floral","coconut","sweet"],"Paradise lust. Tiare and coconut. Tropical luxury."),
m("The Different Company","Oriental Lounge EDP","unisex",2004,4.05,["fall","winter"],["oud","floral","spicy","amber"],"Oriental lounge. Cardamom and orris. Sophisticated."),
m("Liquides Imaginaires","Blanche Bete EDP","unisex",2013,4.08,["spring","fall"],["musk","white floral","powdery","clean"],"White beast. Clean musk and white flowers. Pure."),
m("Profumum Roma","Ambra Aurea EDP","unisex",2001,4.28,["fall","winter"],["amber","sweet","musky","vanilla"],"Golden amber. Pure ambergris. Ancient luxury."),
m("Etro","Shaal Nur EDP","unisex",2004,4.05,["fall","winter"],["oud","rose","amber","spicy"],"Kashmir luxury. Saffron and rose oud. Indian."),
m("Histoires de Parfums","1740 EDP","male",2011,4.08,["fall","winter"],["leather","spicy","amber","woody"],"1740 Marquis de Sade. Dark leather. Scandalous."),
m("Lolita Lempicka","Mon Premier Parfum EDP","female",2007,3.72,["spring","fall"],["floral","sweet","gourmand","iris"],"Mon premier. Violet and anise. First Lolita."),
m("Reminiscence","Patchouli EDP","unisex",1970,3.98,["fall","winter"],["patchouli","earthy","woody","musk"],"Pure patchouli since 1970. Hippie heritage."),
m("Comptoir Sud Pacifique","Vanille Coco EDP","female",2018,3.72,["spring","summer"],["vanilla","coconut","floral","sweet"],"Coconut vanilla. Tropical warmth. Pacific luxury."),
m("Czech Czech","Black Nuit de Bakelite EDT","unisex",2011,3.88,["fall","winter"],["floral","aldehydic","smoky","woody"],"Bakelite nights. Tuberose and smoke. Czech artistry."),
m("Floris","Lily of the Valley EDT","female",1876,3.85,["spring","summer"],["floral","white floral","fresh","powdery"],"Heritage lily. English 1876. Garden classic."),
m("Roger Vivier","Je T'Aime EDP","female",2019,3.88,["spring","fall"],["floral","rose","soft","musk"],"I love you. Rose and sandalwood. Shoe luxury."),
m("Shiseido","Zen EDP","female",1964,3.88,["fall","winter"],["floral","oriental","amber","woody"],"Zen harmony. Rose and sandalwood. Meditative."),
m("Houbigant","Fougere Royale EDT","male",1882,4.08,["fall","winter"],["fougere","lavender","oakmoss","coumarin"],"The first fougere 1882. Lavender and oakmoss."),
m("Coty","L'Aimant EDP","female",1927,3.75,["spring","fall"],["floral","aldehydic","powdery","oriental"],"The loved one. 1927 French chypre. Art deco."),
];

const existing=JSON.parse(readFileSync(DATA,"utf-8"));
console.log(`Mevcut: ${existing.length}`);
const seen=new Map(existing.map(p=>[`${p.brand}|${p.name}`.toLowerCase().trim(),true]));
let added=0;const merged=[...existing];
for(const p of N){
  const key=`${p.brand}|${p.name}`.toLowerCase().trim();
  if(!seen.has(key)){seen.set(key,true);merged.push(p);added++;}
}
merged.forEach((p,i)=>{p.id=String(i+1);});
writeFileSync(DATA,JSON.stringify(merged,null,2),"utf-8");
console.log(`Eklenen: ${added}`);
console.log(`Toplam: ${merged.length}`);
