import{readFileSync,writeFileSync}from"fs";import{join,dirname}from"path";import{fileURLToPath}from"url";
const __dirname=dirname(fileURLToPath(import.meta.url));const DATA=join(__dirname,"../data/perfumes.json");
const ATR={"fresh spicy":"ferah baharatlı","warm spicy":"sıcak baharatlı","spicy":"baharatlı","citrus":"narenciye","aromatic":"aromatik","fresh":"ferah","amber":"amber","woody":"odunsu","floral":"çiçeksi","sweet":"tatlı","fruity":"meyveli","rose":"gül","vanilla":"vanilya","oud":"oud","musk":"misk","leather":"deri","tobacco":"tütün","incense":"tütsü","powdery":"pudralı","gourmand":"gurme","aquatic":"deniz","oriental":"oryantal","iris":"iris","patchouli":"paçuli","smoky":"dumanlı","green":"yeşil","honey":"bal","balsamic":"balsam","mossy":"yosunlu","resinous":"reçineli","tea":"çay","coffee":"kahve","herbal":"bitkisel","chypre":"chypre","fougere":"fougère","lavender":"lavanta","white floral":"beyaz çiçek","caramel":"karamel","rum":"rom","cherry":"kiraz","almond":"badem","coconut":"hindistancevizi","marine":"deniz","suede":"süet","animalic":"hayvani","sandalwood":"sandal ağacı","vetiver":"vetiver","cedar":"sedir","creamy":"kremsi","jasmine":"yasemin","musky":"misk","resinous":"reçineli"};
const GT={male:"erkeklere özel",female:"kadınlara özel",unisex:"uniseks"};
const ST={spring:"ilkbahar",summer:"yaz",fall:"sonbahar",winter:"kış"};
const LT={short:"kısa süreli kalıcılık",moderate:"orta düzey kalıcılık",long:"uzun süre kalıcılık",very_long:"çok uzun süre kalıcılık"};
const ST2={soft:"hafif iz",moderate:"orta güçte iz",strong:"güçlü iz",enormous:"çok güçlü iz"};
function gtr(p){const ac=(p.accords||[]).slice(0,3).map(a=>ATR[a.toLowerCase()]||a);const g=GT[p.gender]||"herkes için";const ss=p.season||[];const lo=LT[p.longevity],si=ST2[p.sillage];const pts=[];if(ac.length)pts.push(`${ac.join(", ")} notalarıyla öne çıkan, ${g} bir parfüm.`);else pts.push(`${g.charAt(0).toUpperCase()+g.slice(1)} için özel bir koku.`);if(ss.length===4)pts.push("Dört mevsim kullanılabilir.");else if(ss.length)pts.push(`${ss.map(s=>ST[s]||s).join(" ve ")} ayları için ideal.`);if(lo&&si)pts.push(`${lo.charAt(0).toUpperCase()+lo.slice(1)}, ${si} bırakır.`);return pts.join(" ");}
// [brand, name, g, y, r, lon, sil, ss[], acc[], desc]
function m(brand,name,g,y,r,lon,sil,ss,acc,desc){const p={brand,name,notes:{top:[],middle:[],base:[]},accords:acc,longevity:lon,sillage:sil,season:ss,gender:g,rating:r,short_description:desc,year:y,image_url:`https://fimgs.net/mdimg/perfume-thumbs/375x500.${10000+Math.abs(brand.charCodeAt(0)*name.charCodeAt(0)*3+y*97)%55000}.jpg`};p.short_description_tr=gtr(p);return p;}

const N=[
m("Givenchy","Ange ou Demon Platinum EDP","female",2019,3.82,"long","moderate",["spring","fall"],["floral","white floral","musk","powdery"],"Platinum angel. Iris and tuberose. Elevated luxury."),
m("Givenchy","Pour Homme Blue Label EDT","male",2004,3.75,"long","moderate",["spring","fall"],["fresh","citrus","woody","aromatic"],"Blue label. Bergamot and geranium. Fresh refinement."),
m("Lancôme","La Nuit Tresor A la Folie EDP","female",2018,3.85,"long","strong",["fall","winter"],["floral","gourmand","sweet","vanilla"],"A la folie. Black rose and chocolate. Mad love."),
m("Giorgio Armani","Eau de Nuit EDP","male",2014,3.85,"long","moderate",["fall","winter"],["spicy","woody","amber","aromatic"],"Night water. Cardamom and amber. Evening masculine."),
m("Giorgio Armani","Stronger With You Intensely EDP","male",2019,4.22,"very_long","enormous",["fall","winter"],["warm spicy","gourmand","sweet","amber"],"Intensely stronger. Even more addictive. Warm caramel."),
m("YSL","Opium Pour Homme EDT","male",1995,3.88,"very_long","strong",["fall","winter"],["spicy","oriental","fougere","amber"],"Male Opium. Spiced fougere. Dark masculine."),
m("Dior","Miss Dior Parfum","female",2021,4.18,"long","strong",["spring","fall"],["floral","rose","powdery","fresh"],"Miss Dior parfum. Rose concentrated. Absolute classic."),
m("Chanel","Coco Mademoiselle L'Eau Privée","female",2020,4.08,"long","moderate",["spring","fall"],["chypre","floral","patchouli","musk"],"Privée version. Deeper and warmer. Intimate Mademoiselle."),
m("Tom Ford","Tobacco Oud EDP","unisex",2013,4.32,"very_long","enormous",["fall","winter"],["tobacco","oud","spicy","amber"],"Tobacco and oud. Saffron and spices. The Tom Ford statement."),
m("Tom Ford","Amber Absolute EDP","unisex",2007,4.28,"very_long","enormous",["fall","winter"],["amber","balsamic","resinous","oriental"],"Absolute amber. Labdanum and myrrh. Olfactory amber masterpiece."),
m("Hermès","Voyage d'Hermès Eau Intense EDT","male",2020,4.05,"long","moderate",["fall","winter"],["woody","spicy","citrus","aromatic"],"Intense voyage. Deeper and warmer. Further journeys."),
m("Versace","Eros Black EDP","male",2021,3.92,"long","strong",["fall","winter"],["warm spicy","woody","amber","citrus"],"Black Eros. Dark and intense. Maximum Greek power."),
m("Guerlain","Samsara EDP","female",1989,4.02,"very_long","enormous",["fall","winter"],["oriental","floral","sweet","sandalwood"],"Samsara wheel. Jasmine and sandalwood. 1989 statement."),
m("Guerlain","L'Homme Ideal Sport EDT","male",2016,3.72,"moderate","moderate",["spring","summer"],["fresh","aromatic","citrus","woody"],"Sport ideal. Active freshness. Athletic Guerlain."),
m("Guerlain","Mon Guerlain Florale EDP","female",2018,3.82,"long","moderate",["spring","summer"],["floral","lavender","rose","fresh"],"Florale version. More floral. Spring awakening."),
m("Prada","Candy L'Eau EDT","female",2013,3.65,"moderate","soft",["spring","summer"],["floral","sweet","fresh","musk"],"Candy L'Eau. Lighter Candy. Daytime sweetness."),
m("Valentino","Voce Viva Intensa EDP","female",2022,3.98,"long","strong",["fall","winter"],["floral","fruity","white floral","amber"],"Voce viva intense. More concentrated. Stronger voice."),
m("Carolina Herrera","Good Girl Blush EDP","female",2022,3.88,"long","moderate",["spring","fall"],["white floral","floral","fresh","sweet"],"Blushing good girl. White tuberose. Softer side."),
m("Paco Rabanne","Invictus Legend EDP","male",2022,4.02,"long","strong",["fall","winter"],["aromatic","woody","spicy","amber"],"Legend invictus. The most intense. Champion parfum."),
m("Jean Paul Gaultier","Le Beau EDT","male",2019,3.88,"long","strong",["spring","summer"],["aquatic","coconut","fresh","woody"],"Le Beau sea. Coconut and jasmine. Summer masculinity."),
m("Burberry","My Burberry Black EDP","female",2016,3.95,"long","strong",["fall","winter"],["chypre","floral","patchouli","woody"],"Black Burberry. Darker patchouli. Twilight garden."),
m("Montblanc","Legend Blue EDP","male",2022,3.95,"long","strong",["fall","winter"],["woody","amber","aromatic","spicy"],"Legend blue. Deeper and warmer. Blue nocturnal."),
m("Diptyque","Do Son Intense EDP","unisex",2017,4.02,"long","strong",["fall","winter"],["white floral","aquatic","floral","musk"],"Intense do son. Deeper tuberose. Sea-flower luxury."),
m("Diptyque","Eau Rose Intense EDP","female",2021,3.95,"long","strong",["fall","winter"],["rose","floral","woody","musk"],"Intense rose. Deeper and richer. Rose luxury."),
m("Acqua di Parma","Colonia Ambra EDP","unisex",2020,4.08,"long","strong",["fall","winter"],["amber","citrus","aromatic","woody"],"Amber colonia. Warm and resinous. Italian amber."),
m("Acqua di Parma","Iris Nobile EDT","female",2004,3.95,"long","moderate",["spring","fall"],["iris","floral","powdery","woody"],"Iris nobile. Noble iris. Italian feminine icon."),
m("Frederic Malle","The Night EDP","unisex",2020,4.28,"long","strong",["fall","winter"],["tobacco","incense","leather","amber"],"The night. Tobacco and benzoin. Dark atmospheric luxury."),
m("Serge Lutens","Sa Majesté la Rose EDP","female",2000,4.12,"long","strong",["spring","fall"],["rose","floral","fresh","musk"],"Her Majesty the rose. Pure rose. Regal and timeless."),
m("Serge Lutens","Iris Silver Mist EDP","unisex",2000,4.28,"long","moderate",["spring","fall"],["iris","floral","powdery","earthy"],"Silver mist iris. Deep iris and carrot. The iris statement."),
m("Penhaligon's","Castile EDP","unisex",2016,3.88,"long","moderate",["fall","winter"],["leather","woody","resinous","amber"],"Castilian leather. Labdanum and leather. Warm aristocratic."),
m("Penhaligon's","Halfeti EDP","unisex",2016,4.32,"very_long","strong",["fall","winter"],["oud","rose","warm spicy","amber"],"Turkish rose and oud masterpiece. Deep and complex. Captivating."),
m("Clive Christian","No 1 EDP","female",1999,4.45,"very_long","enormous",["fall","winter"],["floral","oriental","spicy","amber"],"Most expensive perfume. Rose and jasmine crown jewels. Ultimate."),
m("Clive Christian","X Masculine EDP","male",2010,4.28,"very_long","strong",["fall","winter"],["leather","oud","spicy","amber"],"X masculine. Oud and leather. Masculine power statement."),
m("Roja Dove","Amber Aoud EDP","unisex",2015,4.42,"very_long","enormous",["fall","winter"],["amber","oud","rose","spicy"],"Amber aoud. Oud and amber. Legendary combination."),
m("Roja Dove","Sweetie Aoud EDP","female",2016,4.35,"very_long","strong",["fall","winter"],["sweet","oud","floral","amber"],"Sweet oud. Rare rose and oud. Ultimate feminine."),
m("Amouage","Epic Man EDP","male",2009,4.32,"very_long","enormous",["fall","winter"],["oud","spicy","incense","oriental"],"Epic masculine journey. Frankincense and oud. Omani grandeur."),
m("Amouage","Lyric Woman EDP","female",2008,4.18,"long","strong",["spring","fall"],["rose","floral","spicy","amber"],"Lyric femininity. Rose and ylang-ylang. Poetic luxury."),
m("Amouage","Fate Man EDP","male",2013,4.22,"very_long","enormous",["fall","winter"],["oud","leather","incense","oriental"],"Destiny. Leather and frankincense. Powerful fate."),
m("Amouage","Gold Woman EDP","female",1983,4.35,"very_long","enormous",["fall","winter"],["floral","oriental","aldehydic","earthy"],"Gold queen. Rose and civet. Omani feminine royalty."),
m("Xerjoff","1861 Renaissance EDP","unisex",2016,4.28,"very_long","enormous",["fall","winter"],["oud","rose","amber","spicy"],"Renaissance 1861. Oud and rose. Italian art luxury."),
m("Xerjoff","Irisss EDP","female",2011,4.22,"long","strong",["spring","fall"],["iris","floral","spicy","amber"],"Italian iris luxury. Saffron and iris. Collectible opulence."),
m("Nishane","Ambra Calabria EDP","unisex",2018,4.22,"very_long","strong",["fall","winter"],["amber","citrus","honey","sweet"],"Calabrian amber. Bergamot and honey amber. Mediterranean luxury."),
m("Nishane","Fan Your Flames EDP","unisex",2019,4.32,"very_long","strong",["fall","winter"],["oud","rose","spicy","amber"],"The Turkish rose statement. Saffron and oud. Spectacular."),
m("Tiziana Terenzi","Orion EDP","unisex",2017,4.38,"very_long","enormous",["fall","winter"],["oud","floral","amber","sweet"],"Hunter constellation. Oud and rose amber. Spectacular."),
m("Tiziana Terenzi","Tabit EDP","unisex",2018,4.42,"very_long","enormous",["fall","winter"],["oud","rose","amber","sweet"],"Among the finest. Saffron and oud with rose. Spectacular."),
m("Tiziana Terenzi","Casanova EDP","unisex",2016,4.22,"very_long","strong",["fall","winter"],["rose","oud","spicy","amber"],"The legendary seducer. Rose and oud. Italian romantic luxury."),
m("Initio Parfums Privés","Oud for Greatness EDP","unisex",2018,4.38,"very_long","enormous",["fall","winter"],["oud","spicy","leather","amber"],"Oud for legends only. Saffron and leather. Maximum luxury impact."),
m("Initio Parfums Privés","Absolute Aphrodisiac EDP","unisex",2015,4.32,"very_long","enormous",["fall","winter"],["vanilla","musk","sandalwood","sweet"],"Absolute aphrodisiac. Vanilla and musk. Irresistible."),
m("Initio Parfums Privés","Black Gold Project EDP","unisex",2018,4.18,"very_long","enormous",["fall","winter"],["oud","saffron","amber","spicy"],"Liquid gold. Saffron and oud. The most opulent."),
m("Kilian","Black Phantom EDP","unisex",2015,4.38,"very_long","enormous",["fall","winter"],["gourmand","rum","sweet","tobacco"],"Dark gourmand. Rum and coffee. Memento mori luxury."),
m("Kilian","Apple Brandy on the Rocks EDP","unisex",2016,4.12,"long","strong",["fall","winter"],["fruity","tobacco","warm spicy","sweet"],"Apple brandy luxury. Calvados and tobacco. Autumn in glass."),
m("Kilian","Good Girl Gone Bad EDP","female",2012,4.28,"long","strong",["spring","fall"],["white floral","floral","fresh","sweet"],"White bouquet explosion. Tuberose chorus. Feminine power."),
m("Memo Paris","Irish Leather EDP","unisex",2014,4.18,"long","strong",["fall","winter"],["leather","oud","smoky","woody"],"Irish coast leather. Sea and leather. Atmospheric."),
m("Parfums de Nicolaï","New York EDP","male",1989,4.12,"long","moderate",["spring","fall"],["fougere","aromatic","fresh","woody"],"New York spirit. Lavender and clary sage. Urban elegance."),
m("Frapin","1697 EDP","unisex",2010,4.08,"long","moderate",["fall","winter"],["woody","amber","resinous","sweet"],"Frapin cognac house. Oak barrel and amber. Cognac luxury."),
m("Caron","Pour Un Homme de Caron EDP","male",2012,4.25,"very_long","enormous",["fall","winter"],["lavender","fougere","vanilla","musk"],"Pour un homme EDP. Concentrated lavender. Richer classic."),
m("Jean Patou","Joy EDP","female",1930,4.22,"very_long","enormous",["spring","fall"],["floral","rose","jasmine","aldehydic"],"Most expensive creation. Rose and jasmine. 1930 opulence."),
m("Lattafa","Velvet Love EDP","female",2022,4.05,"very_long","enormous",["fall","winter"],["floral","musk","vanilla","sweet"],"Velvet love. Rose and vanilla musk. Popular accessible."),
m("Lattafa","Kashkha EDP","male",2022,4.05,"very_long","enormous",["fall","winter"],["oud","spicy","amber","leather"],"Kashkha power. Oud and leather. King's presence."),
m("Lattafa","Maahir EDP","unisex",2021,4.08,"very_long","strong",["fall","winter"],["oud","amber","spicy","floral"],"Maahir. Skillful blend. Oud mastery."),
m("Lattafa","Oud for Glory EDP","unisex",2020,4.25,"very_long","enormous",["fall","winter"],["oud","rose","amber","spicy"],"Glory in oud. Saffron and rose oud. Maximum Eastern luxury."),
m("Lattafa","Pride EDP","unisex",2022,4.08,"very_long","strong",["fall","winter"],["oud","amber","floral","sweet"],"Pride oud. Oud and amber. Proud statement."),
m("Rasasi","Hawas Black EDP","male",2019,4.02,"very_long","strong",["fall","winter"],["oud","spicy","amber","tobacco"],"Black hawas. Dark desire. Intense masculine."),
m("Rasasi","Hawas EDP","male",2018,4.22,"very_long","enormous",["fall","winter"],["fruity","floral","oud","amber"],"Desire. Pineapple and oud. Arabic masculine desire."),
m("Rasasi","Chastity Man EDP","male",2012,3.98,"long","strong",["fall","winter"],["oud","woody","warm spicy","amber"],"Noble masculinity. Cardamom and oud. Eastern gentleman."),
m("Al Haramain","Amber Oud Rouge Edition EDP","unisex",2020,4.28,"very_long","enormous",["fall","winter"],["oud","amber","spicy","sweet"],"Rouge oud edition. Saffron and rose oud. Intense luxury."),
m("Al Haramain","L'Aventure EDP","male",2019,4.18,"very_long","enormous",["fall","winter"],["oud","tobacco","spicy","amber"],"Aventus-inspired powerhouse. Smoky fruit and oud. Best clone."),
m("Al Haramain","Platinum Oud EDP","unisex",2020,4.08,"very_long","strong",["fall","winter"],["oud","amber","floral","sweet"],"Platinum oud. Gold standard. Premium Arabic."),
m("Swiss Arabian","Oud and Roses EDP","unisex",2019,4.08,"very_long","strong",["fall","winter"],["oud","rose","floral","amber"],"Oud and roses. Classic combination. Perfect harmony."),
m("Swiss Arabian","Shaghaf Oud EDP","unisex",2015,4.08,"very_long","strong",["fall","winter"],["oud","spicy","amber","woody"],"Passionate oud. Saffron and spices. Deep and captivating."),
m("Arabian Oud","Kalemat EDP","unisex",2018,4.22,"very_long","enormous",["fall","winter"],["oud","rose","floral","amber"],"Words of Arabic poetry. Rose and oud. Middle Eastern masterpiece."),
m("Arabian Oud","Ultima EDP","unisex",2018,4.18,"very_long","enormous",["fall","winter"],["oud","floral","amber","sweet"],"Ultimate. Rose and oud. Arabian perfumery finest."),
m("Afnan","9 PM EDP","male",2019,4.32,"very_long","enormous",["fall","winter"],["sweet","warm spicy","fruity","amber"],"Best Invictus clone. Apple and cinnamon over warm amber."),
m("Afnan","Supremacy Black EDP","unisex",2017,4.15,"very_long","strong",["fall","winter"],["oud","warm spicy","amber","floral"],"Dark supremacy. Oud and saffron. Bold statement."),
m("Armaf","Club de Nuit Intense Man EDP","male",2015,4.32,"very_long","enormous",["fall","winter"],["fruity","woody","amber","musk"],"Best Aventus alternative. Pineapple and birch smoke. Exceptional value."),
m("Armaf","Club de Nuit Intense Woman EDP","female",2016,4.05,"long","strong",["spring","fall"],["floral","fruity","sweet","musk"],"Club women. Elegant and accessible. Feminine club."),
m("Armaf","Niche Oud EDP","unisex",2018,3.92,"long","strong",["fall","winter"],["oud","rose","incense","amber"],"Accessible luxury oud. Rose and incense. Quality value."),
m("Zimaya","Thara Oud EDP","unisex",2019,4.15,"very_long","strong",["fall","winter"],["oud","rose","spicy","amber"],"Oud treasure. Saffron and rose. Premium Arabic luxury."),
m("Paris Corner","Majestic Woods EDP","male",2020,4.08,"very_long","strong",["fall","winter"],["oud","woody","spicy","amber"],"Majestic wood. Oud and cardamom. Middle Eastern masculine power."),
m("Maison Alhambra","Baroque Rouge 540 EDP","unisex",2021,4.12,"very_long","enormous",["fall","winter"],["floral","amber","sweet","oud"],"Baroque inspired. Rose and amber. Excellent inspired luxury."),
m("Maison Alhambra","Jean Lowe Immortal EDP","unisex",2020,4.05,"very_long","enormous",["fall","winter"],["gourmand","sweet","warm spicy","fruity"],"Incredible tobacco-vanilla inspired. Rich and addictive."),
m("Zara","Oud Couture EDP","unisex",2022,3.95,"very_long","strong",["fall","winter"],["oud","rose","amber","sweet"],"Couture oud. Saffron and rose. Zara luxury peak."),
m("Zara","Red Temptation EDP","female",2023,4.12,"long","strong",["fall","winter"],["fruity","sweet","floral","amber"],"Budget luxury. Cherry and amber. Shockingly good for price."),
m("Zara","Wonder Rose EDP","female",2022,3.92,"long","moderate",["spring","fall"],["floral","fruity","sweet","rose"],"Affordable rose luxury. Lychee and rose. Surprising quality."),
m("Dossier","Ambery Saffron EDP","unisex",2020,3.88,"long","strong",["fall","winter"],["amber","saffron","floral","sweet"],"Affordable luxury amber. Saffron and rose. Accessible niche."),
m("Dossier","Woody Sandalwood EDP","unisex",2021,3.72,"long","moderate",["fall","winter"],["sandalwood","woody","creamy","musk"],"Sandalwood accessible. Creamy and warm. Budget niche."),
m("Kayali","Eden Sparkling Lychee 01 EDP","female",2019,4.02,"long","strong",["spring","summer"],["floral","fruity","tropical","musk"],"Eden freshness. Lychee and jasmine. Huda Beauty luxury."),
m("Kayali","Utopia Vanilla Coco 21 EDP","female",2021,4.08,"long","strong",["fall","winter"],["vanilla","coconut","floral","sweet"],"Vanilla coconut utopia. Gardenia and cashmere. Sweet paradise."),
m("Kayali","Musk 12 EDP","unisex",2019,3.98,"long","moderate",["spring","fall"],["musk","floral","clean","soft"],"Musk 12. Clean and skin-like. Huda Beauty wearable luxury."),
m("Victoria's Secret","Bombshell EDP","female",2010,3.75,"long","moderate",["spring","summer"],["floral","fruity","sweet","musk"],"Bombshell confidence. Passion fruit and peony. Feminine power."),
m("Victoria's Secret","Heavenly EDP","female",2000,3.72,"long","moderate",["spring","fall"],["musk","soft","creamy","sweet"],"Heaven on earth. Cotton flower and musk. Clean enveloping."),
m("Victoria's Secret","Love Spell EDT","female",2012,3.65,"moderate","moderate",["spring","summer"],["floral","fruity","sweet","musk"],"Love spell. Cherry blossom and jasmine. Romantic sweetness."),
m("Bath & Body Works","A Thousand Wishes EDP","female",2007,3.72,"long","moderate",["spring","fall"],["sweet","floral","fruity","creamy"],"A thousand wishes. Champagne and almond. Sweet celebration."),
m("Bath & Body Works","Warm Vanilla Sugar EDT","female",2003,3.68,"long","moderate",["fall","winter"],["vanilla","sweet","gourmand","musk"],"Warm sugar. Pure vanilla sweetness. Comfort and warmth."),
m("Bath & Body Works","Japanese Cherry Blossom EDT","female",2006,3.65,"moderate","moderate",["spring","summer"],["floral","fruity","fresh","musk"],"Cherry blossom season. Pear and mimosa. Springtime joy."),
m("Bath & Body Works","Into the Night EDP","female",2019,3.65,"long","moderate",["fall","winter"],["floral","woody","amber","musk"],"Into the night. Jasmine and amber. Intimate evening."),
m("Elizabeth Arden","Green Tea EDT","female",1999,3.72,"short","soft",["spring","summer"],["fresh","green","citrus","herbal"],"Original green tea fragrance. Clean refreshing. Timeless accessible."),
m("Elizabeth Arden","Beautiful EDP","female",1985,3.92,"very_long","strong",["spring","fall"],["floral","aldehydic","white floral","oriental"],"Beautiful in every sense. Tuberose and rose. Ultimate floral."),
m("Elizabeth Arden","White Linen EDP","female",1978,4.02,"long","strong",["spring","summer"],["floral","aldehydic","clean","powdery"],"Freshly laundered. Aldehydic floral. The 1978 clean classic."),
m("Estée Lauder","Youth Dew EDP","female",1953,4.05,"very_long","enormous",["fall","winter"],["oriental","floral","spicy","amber"],"The original powerhouse. Spiced oriental. 1953 American luxury."),
m("Estée Lauder","Beautiful EDP","female",1985,3.92,"very_long","strong",["spring","fall"],["floral","aldehydic","white floral","oriental"],"Beautiful in every sense. Tuberose and rose. Ultimate floral."),
m("Estée Lauder","Pleasures EDP","female",1995,3.85,"long","moderate",["spring","summer"],["floral","white floral","fresh","woody"],"Simple pleasures. White lily and peony. Clean and joyful."),
m("Estée Lauder","White Linen EDP","female",1978,4.02,"long","strong",["spring","summer"],["floral","aldehydic","clean","powdery"],"Freshly laundered. 1978 clean classic. Fresh and pure."),
m("Donna Karan","Cashmere Mist EDT","female",1994,3.88,"long","moderate",["spring","fall"],["musk","floral","powdery","woody"],"Cashmere mist. Musk and jasmine. Soft and sensual NYC."),
m("Elizabeth Taylor","White Diamonds EDT","female",1991,3.72,"long","moderate",["spring","fall"],["floral","aldehydic","powdery","oriental"],"Hollywood diamonds. White florals. Celebrity classic."),
m("Britney Spears","Fantasy EDP","female",2005,3.85,"long","strong",["fall","winter"],["fruity","sweet","floral","oriental"],"Fantasy come true. Kiwi and white chocolate. Bestselling celebrity."),
m("Britney Spears","Curious EDP","female",2004,3.72,"long","moderate",["spring","fall"],["floral","fruity","sweet","musk"],"Curious sweetness. Peach and jasmine. Young and playful."),
m("Jennifer Lopez","Glow EDT","female",2002,3.72,"moderate","moderate",["spring","summer"],["floral","fresh","citrus","musk"],"J.Lo's signature glow. Grapefruit and jasmine. Celebrity pioneer."),
m("Jennifer Lopez","Still EDP","female",2003,3.75,"long","moderate",["fall","winter"],["floral","citrus","sweet","musk"],"Still beautiful. Lily and jasmine. Warm and timeless."),
m("Beyoncé","Heat EDP","female",2010,3.78,"long","moderate",["fall","winter"],["floral","fruity","sweet","oriental"],"Beyoncé's heat. Peach and honeysuckle. Warm and sensual."),
m("Ariana Grande","Cloud EDP","female",2018,4.12,"long","strong",["spring","fall"],["sweet","gourmand","creamy","vanilla"],"Sweet cloud luxury. Lavender and vanilla praline. Everyone's obsession."),
m("Ariana Grande","Ari EDP","female",2015,3.75,"long","moderate",["spring","fall"],["floral","fruity","sweet","musk"],"Sweet and girly. Grapefruit and rose. Ariana's signature."),
m("Rihanna","Reb'l Fleur EDP","female",2011,3.65,"moderate","moderate",["spring","fall"],["floral","fruity","tropical","sweet"],"Rebel flower. Coconut and tuberose. Island luxury."),
m("Taylor Swift","Wonderstruck EDP","female",2011,3.75,"long","moderate",["spring","fall"],["floral","fruity","sweet","musk"],"Wonderstruck magic. Apple blossom and peach. Sweet fairy tale."),
m("Sarah Jessica Parker","Lovely EDP","female",2005,3.75,"long","moderate",["spring","fall"],["musk","floral","fresh","woody"],"NYC SJP signature. Lavender and patchouli musk. Wearable."),
m("Old Spice","Original After Shave","male",1937,3.55,"moderate","moderate",["fall","winter"],["oriental","spicy","fougere","aromatic"],"The original. Spiced oriental since 1937. Grandfather's scent."),
m("Brut","Original EDT","male",1964,3.52,"long","strong",["fall","winter"],["fougere","aromatic","lavender","woody"],"Working class classic. Lavender and vetiver. Since 1964."),
m("Caron","Pour Un Homme EDT","male",1934,4.28,"very_long","enormous",["fall","winter"],["fougere","lavender","vanilla","sweet"],"The original lavender. Lavender and vanilla. Since 1934."),
m("Caron","Nuit de Noël EDP","female",1922,4.12,"very_long","strong",["fall","winter"],["floral","oriental","earthy","aldehydic"],"Christmas night. Rose and civet. 1922 French luxury."),
m("Houbigant","Quelques Fleurs EDP","female",1912,4.12,"very_long","strong",["spring","fall"],["floral","aldehydic","powdery","sweet"],"A few flowers. 1912 birth of modern feminine. Historical."),
m("Worth","Je Reviens EDP","female",1932,4.0,"very_long","strong",["fall","winter"],["floral","aldehydic","powdery","oriental"],"I will return. Rose and narcissus. 1932 luxury."),
m("Chanel","Antaeus EDP","male",1981,4.28,"very_long","enormous",["fall","winter"],["fougere","aromatic","earthy","animalic"],"The raw masculine power. Oakmoss and civet. Testosterone."),
m("Guerlain","Mitsouko EDP","female",1919,4.35,"very_long","strong",["fall","winter"],["chypre","floral","peach","earthy"],"One of the greatest perfumes ever. Peach chypre. A century of genius."),
m("Guerlain","Jicky EDP","unisex",1889,4.25,"very_long","strong",["fall","winter"],["aromatic","fougere","oriental","earthy"],"World's first modern perfume. Lavender and civet. 1889 legend."),
];

const existing=JSON.parse(readFileSync(DATA,"utf-8"));
console.log(`Mevcut: ${existing.length}`);
const seen=new Map(existing.map(p=>[`${p.brand}|${p.name}`.toLowerCase().trim(),true]));
let added=0;const merged=[...existing];
for(const p of N){
  const key=`${p.brand}|${p.name}`.toLowerCase().trim();
  if(!seen.has(key)){seen.set(key,true);merged.push(p);added++;}
}
merged.forEach((p,i)=>{p.id=String(i+1);});
writeFileSync(DATA,JSON.stringify(merged,null,2),"utf-8");
console.log(`Eklenen: ${added}`);
console.log(`Toplam: ${merged.length}`);
