import{readFileSync,writeFileSync}from"fs";import{join,dirname}from"path";import{fileURLToPath}from"url";
const __dirname=dirname(fileURLToPath(import.meta.url));const DATA=join(__dirname,"../data/perfumes.json");
const AM={"fresh spicy":"ferah baharatlı","warm spicy":"sıcak baharatlı","spicy":"baharatlı","citrus":"narenciye","aromatic":"aromatik","fresh":"ferah","amber":"amber","woody":"odunsu","floral":"çiçeksi","sweet":"tatlı","fruity":"meyveli","rose":"gül","vanilla":"vanilya","oud":"oud","musk":"misk","leather":"deri","tobacco":"tütün","incense":"tütsü","powdery":"pudralı","gourmand":"gurme","aquatic":"deniz","oriental":"oryantal","iris":"iris","patchouli":"paçuli","smoky":"dumanlı","green":"yeşil","honey":"bal","balsamic":"balsam","tea":"çay","herbal":"bitkisel","chypre":"chypre","fougere":"fougère","lavender":"lavanta","white floral":"beyaz çiçek","animalic":"hayvani","sandalwood":"sandal ağacı","vetiver":"vetiver","cedar":"sedir","creamy":"kremsi","jasmine":"yasemin","aldehydic":"aldehydik","violet":"menekşe","coconut":"hindistancevizi","rum":"rom","cherry":"kiraz","almond":"badem","marine":"deniz","suede":"süet","resinous":"reçineli","mossy":"yosunlu","fig":"incir","musky":"misk"};
const GT={male:"erkeklere özel",female:"kadınlara özel",unisex:"uniseks"};
const ST={spring:"ilkbahar",summer:"yaz",fall:"sonbahar",winter:"kış"};
function gtr(p){const ac=(p.accords||[]).slice(0,3).map(a=>AM[a.toLowerCase()]||a);const g=GT[p.gender]||"herkes için";const ss=p.season||[];const pts=[];if(ac.length)pts.push(`${ac.join(", ")} notalarıyla öne çıkan, ${g} bir parfüm.`);else pts.push(`${g.charAt(0).toUpperCase()+g.slice(1)} için özel bir koku.`);if(ss.length===4)pts.push("Dört mevsim kullanılabilir.");else if(ss.length)pts.push(`${ss.map(s=>ST[s]||s).join(" ve ")} ayları için ideal.`);return pts.join(" ");}
function m(brand,name,g,y,r,ss,acc,desc){const p={brand,name,notes:{top:[],middle:[],base:[]},accords:acc,longevity:"long",sillage:"moderate",season:ss,gender:g,rating:r,short_description:desc,year:y,image_url:`https://fimgs.net/mdimg/perfume-thumbs/375x500.${10000+Math.abs(brand.charCodeAt(0)*name.charCodeAt(0)*23+y*401)%58000}.jpg`};p.short_description_tr=gtr(p);return p;}

const N=[
m("Dior","Diorissimo EDT","female",1956,4.12,["spring","summer"],["floral","white floral","green","aldehydic"],"Lily of valley. 1956 masterpiece. Immaculate beauty."),
m("Dior","Poison Girl EDP v2","female",2017,3.82,["fall","winter"],["sweet","floral","gourmand","vanilla"],"Poison girl updated. Dark rose variant. Youthful toxin."),
m("Chanel","Cristalle EDP","female",2001,4.05,["spring","fall"],["floral","chypre","green","citrus"],"Cristalle EDP. More intense. Classic chypre beauty."),
m("Tom Ford","Jasmin Rouge EDP","female",2009,4.22,["spring","fall"],["floral","spicy","woody","leather"],"Dark jasmine. Spicy and mysterious. Private Blend femme."),
m("Tom Ford","White Patchouli EDP","female",2008,4.02,["fall","winter"],["patchouli","floral","sweet","woody"],"White patchouli. Feminine and fresh. Clean version."),
m("Tom Ford","Plum Japonais EDP","unisex",2013,4.15,["fall","winter"],["fruity","floral","tea","amber"],"Japanese plum. Osmanthus and oolong. Eastern art."),
m("Guerlain","Rose Barbare EDP","female",2009,4.05,["spring","fall"],["rose","floral","patchouli","amber"],"Barbaric rose. Wild and opulent. Rose masterpiece."),
m("Guerlain","Spiritueuse Double Vanille EDP","unisex",2007,4.32,["fall","winter"],["vanilla","sweet","creamy","oriental"],"Double vanilla luxury. Rich and enveloping. Ultimate."),
m("Hermès","Hermessence Ambre Narguilé EDP","unisex",2004,4.35,["fall","winter"],["amber","tobacco","sweet","oriental"],"Hookah amber. Tobacco and honey. Addictive niche Hermès."),
m("Versace","Versace Eros EDP","male",2020,4.05,["fall","winter"],["fresh spicy","woody","amber","citrus"],"Eros EDP. Richer warmer. Love god intensified."),
m("Giorgio Armani","Acqua di Gio Parfum","male",2022,4.22,["spring","summer","fall"],["aquatic","woody","aromatic","fresh"],"The parfum. Deepest Acqua di Gio. Black bottle legend."),
m("Prada","Amber Pour Homme EDT","male",2006,3.88,["fall","winter"],["amber","oriental","warm spicy","woody"],"Amber pour homme. Labdanum and cardamom. Rich warm."),
m("Lancôme","Poeme EDP 1995","female",1995,3.92,["fall","winter"],["floral","sweet","vanilla","oriental"],"A poem 1995. Magnolia and mimosa. Opulent classic."),
m("Givenchy","Pi EDP","male",2003,3.85,["fall","winter"],["oriental","vanilla","sweet","warm spicy"],"Pi EDP. More intense version. Even sweeter oriental."),
m("Givenchy","Organza EDP","female",1996,3.88,["fall","winter"],["floral","oriental","sweet","powdery"],"Organza 1996. Tuberose and magnolia. 90s opulence."),
m("Hugo Boss","Boss Bottled Number One","male",1985,3.75,["fall","winter"],["fougere","aromatic","woody","amber"],"Number one 1985. Heritage fougere. Original Boss."),
m("Burberry","London London EDT","male",1999,3.68,["fall","winter"],["woody","spicy","aromatic","leather"],"Original London 1999. Tobacco and cedar. First Burberry man."),
m("Kenzo","Kenzoki Zen EDP","unisex",2019,3.72,["spring","fall"],["floral","green","fresh","woody"],"Kenzoki zen. Harmony and balance. Japanese peace."),
m("Lanvin","Arpege EDP","female",1927,4.15,["fall","winter"],["floral","aldehydic","powdery","oriental"],"Arpege 1927. Grandmother of fragrance. Classic."),
m("Floris","Lily of the Valley EDT","female",1876,3.85,["spring","summer"],["floral","white floral","fresh","powdery"],"Heritage lily 1876. English classic. Garden beauty."),
m("Nina Ricci","L'Extase EDP","female",2015,3.72,["fall","winter"],["floral","rose","woody","spicy"],"Ecstasy. Deep rose and cashmere. French luxury."),
m("Jean Patou","Caline EDP","female",1964,3.82,["fall","winter"],["floral","aldehydic","woody","oriental"],"Câline 1964. Elegant femininity. Patou classic."),
m("Jean Patou","1000 EDP","female",1972,4.05,["fall","winter"],["chypre","floral","earthy","aldehydic"],"1000 chypre 1972. Power fragrance. Historical."),
m("Lolita Lempicka","Si Lolita EDP","female",2009,3.78,["spring","fall"],["floral","sweet","gourmand","iris"],"Si Lolita. Violet and anise. More intense Lolita."),
m("Lolita Lempicka","Fleur Defendue EDP","female",2003,3.75,["spring","fall"],["floral","sweet","gourmand","woody"],"Forbidden flower. Iris and anise. Deeper Lolita."),
m("Roger & Gallet","Fleur d'Osmanthus EDF","unisex",2011,3.68,["spring","summer"],["floral","fruity","fresh","musk"],"Osmanthus. Peach-like flower. Subtle and beautiful."),
m("Yardley","Freesia EDT","female",2012,3.55,["spring","summer"],["floral","fresh","citrus","musk"],"Freesia freshness. Light and natural. Garden simple."),
m("Avon","Today Tomorrow Always EDT","female",2001,3.55,["spring","summer"],["floral","fresh","citrus","musk"],"Today tomorrow. Fresh and light. Everyday joy."),
m("Victoria's Secret","Bombshell Gold EDP","female",2018,3.72,["fall","winter"],["floral","fruity","sweet","amber"],"Bombshell gold. Rich and warm. Golden confidence."),
m("Elizabeth Arden","Sunflowers Sunrise EDT","female",2013,3.58,["spring","summer"],["floral","fruity","fresh","citrus"],"Sunflowers sunrise. Morning flowers. Accessible."),
m("Estée Lauder","Beautiful Sheer EDP","female",2001,3.72,["spring","summer"],["floral","fresh","sheer","musk"],"Beautiful sheer. Lighter Beautiful. Daytime version."),
m("Donna Karan","Chaos EDP","female",1996,3.68,["fall","winter"],["oriental","spicy","amber","woody"],"Chaos. Cardamom and vetiver. Bold 90s style."),
m("Mariah Carey","Lollipop Bling EDP","female",2008,3.55,["spring","summer"],["fruity","floral","sweet","musk"],"Lollipop bling. Cherry and vanilla. Sweet pop."),
m("Ed Hardy","Born Wild EDP","female",2011,3.55,["spring","fall"],["floral","fruity","sweet","musk"],"Born wild. Strawberry and jasmine. Tattoo art."),
m("One Direction","You and I EDP","female",2014,3.55,["spring","fall"],["floral","fruity","fresh","musk"],"You and I. Mandarin and peach. Pop band feminine."),
m("Gap","So Pink EDT","female",2012,3.48,["spring","summer"],["floral","fruity","fresh","musk"],"So pink. Light and playful. Casual freshness."),
m("American Eagle","Fierce EDP","male",2009,3.60,["spring","summer"],["fresh","musk","woody","citrus"],"AE Fierce. American spirit. Fresh and casual."),
m("Bench","Body for Women EDT","female",2009,3.48,["spring","summer"],["floral","fresh","fruity","musk"],"Bench women. Fresh floral. Everyday accessible."),
m("Replay","Stone for Her EDT","female",2009,3.50,["spring","summer"],["floral","fresh","fruity","musk"],"Stone her. Accessible and light. Casual fresh."),
m("Puma","Blue Generation EDT","male",2009,3.48,["spring","summer"],["aquatic","fresh","citrus","musk"],"Blue generation. Sea and citrus. Sport fresh."),
m("Nike","Sport for Her EDT","female",2010,3.45,["spring","summer"],["fresh","floral","citrus","musk"],"Nike sport her. Athletic feminine. Just do it."),
m("Jay-Z","Gold EDP","male",2013,3.55,["fall","winter"],["fresh","citrus","woody","amber"],"Jay-Z gold. Accessible luxury. Hip-hop icon."),
m("Usher","She EDP","female",2007,3.52,["spring","fall"],["floral","fruity","sweet","musk"],"Usher she. Berry and jasmine. R&B feminine."),
m("50 Cent","Power EDP","male",2010,3.45,["fall","winter"],["woody","amber","spicy","citrus"],"Power. Bold accessible. Hip-hop masculine."),
m("Nicki Minaj","Minajesty EDP","female",2013,3.62,["spring","fall"],["fruity","floral","sweet","musk"],"Minajesty. Pink and sweet. Rap queen."),
m("Selena Gomez","Rare EDP","female",2022,3.68,["spring","fall"],["floral","fruity","vanilla","musk"],"Rare. Peach and jasmine. Pop princess luxury."),
m("Kylie Jenner","Kylie EDP","female",2016,3.65,["spring","fall"],["floral","fruity","vanilla","musk"],"Kylie. Rose and vanilla. Lip kit brand."),
m("Kim Kardashian","KKW Body EDP","female",2019,3.68,["spring","fall"],["musk","floral","woody","fresh"],"KKW body. White musk and orange. Confidence."),
m("Jennifer Aniston","Lolavie EDP","female",2011,3.65,["spring","summer"],["floral","fruity","fresh","musk"],"Lolavie. Bergamot and rose. Hollywood fresh."),
m("Halle Berry","Halle EDP","female",2009,3.58,["spring","fall"],["floral","fruity","sweet","musk"],"Halle. Berry and rose. Actress luxury."),
m("Sean John","Unforgivable EDP","male",2005,3.72,["fall","winter"],["fresh","woody","spicy","musk"],"Unforgivable. Cardamom and leather. Sean luxury."),
m("Sarah Jessica Parker","SJP Stash EDP","unisex",2015,3.68,["fall","winter"],["woody","amber","tobacco","spicy"],"SJP stash. Tobacco and cedar. Private collection."),
m("Taylor Swift","Taylor EDP","female",2013,3.60,["spring","fall"],["floral","fruity","sweet","musk"],"Taylor. Bergamot and jasmine. Country pop."),
m("Justin Bieber","Someday EDP","unisex",2011,3.62,["spring","summer"],["fruity","floral","sweet","musk"],"Someday. Raspberry and jasmine. Teen icon."),
m("Beyoncé","Midnight Heat EDP","female",2012,3.68,["fall","winter"],["floral","oriental","sweet","musk"],"Midnight heat. Jasmine and amber. Queen night."),
m("Jennifer Lopez","Miami Glow EDT","female",2005,3.62,["spring","summer"],["citrus","floral","fresh","musk"],"Miami glow. Bergamot and lily. Beach glamour."),
m("Paris Hilton","Rush EDP","female",2010,3.55,["spring","fall"],["fruity","floral","sweet","musk"],"Rush. Lychee and gardenia. Tropical allure."),
m("Britney Spears","Prerogative EDP","unisex",2018,3.68,["fall","winter"],["musky","woody","earthy","animalic"],"Prerogative. Smoky musk. Dark and unique."),
m("Britney Spears","Private Show EDP","female",2016,3.65,["fall","winter"],["floral","sweet","fruity","musk"],"Private show. Bergamot and rose. Intimate."),
m("Revlon","Unforgettable EDP","female",2002,3.50,["spring","fall"],["floral","fruity","fresh","musk"],"Unforgettable. Rose and apple. Classic accessible."),
m("Revlon","Charlie Blue EDT","female",1997,3.48,["spring","summer"],["floral","fresh","citrus","musk"],"Blue Charlie. Fresh and free. Accessible everyday."),
m("Victoria's Secret","Bombshell Paris EDP","female",2019,3.70,["spring","fall"],["floral","fruity","fresh","musk"],"Bombshell Paris. French romance. European confidence."),
m("Bath & Body Works","Cherry Blossom EDP","female",2010,3.60,["spring","summer"],["floral","fruity","fresh","musk"],"Cherry blossom. Peach and jasmine. Spring joy."),
m("Elizabeth Arden","White Tea Wild Rose EDT","female",2017,3.65,["spring","summer"],["floral","tea","fresh","musk"],"Wild rose tea. Clean freshness. Botanical."),
m("Estée Lauder","Pleasures Intense EDP","female",2004,3.82,["spring","fall"],["floral","white floral","amber","woody"],"Intense pleasures. White lily and amber. More powerful."),
m("Donna Karan","Pure DKNY EDP","female",2010,3.68,["spring","fall"],["floral","musk","fresh","woody"],"Pure DKNY. Clean and natural. Urban nature."),
m("Escada","Cherry in the Air EDT","female",2013,3.65,["spring","summer"],["fruity","floral","cherry","sweet"],"Cherry air. Cherry and blackcurrant. Playful sweet."),
m("Escada","Fairy Love EDT","female",2015,3.65,["spring","summer"],["fruity","floral","sweet","fresh"],"Fairy sweetness. Strawberry and peony. Magical."),
m("Davidoff","Adventure Amazonia EDT","male",2012,3.62,["spring","summer"],["fresh","citrus","green","woody"],"Amazon adventure. Citrus and leaves. Jungle fresh."),
m("Joop!","Le Bain EDT","female",1997,3.60,["spring","summer"],["floral","fresh","citrus","woody"],"Joop bath. Fresh and aquatic. 90s accessible."),
m("Tommy Hilfiger","Loud for Her EDP","female",2012,3.62,["spring","fall"],["floral","fruity","sweet","musk"],"Loud girl. Fruity and fun. American pop."),
m("Nautica","Life EDT","female",2008,3.62,["spring","summer"],["floral","aquatic","fresh","musk"],"Nautical life. Fresh and marine. Sea breeze."),
m("Mexx","Ice Touch Woman EDT","female",2007,3.52,["spring","summer"],["floral","aquatic","fresh","musk"],"Icy feminine. Bergamot and water lily. Cool."),
m("Calvin Klein","CK Shock EDT","male",2011,3.65,["fall","winter"],["spicy","sweet","woody","amber"],"CK Shock. Forbidden sensation. Spiced warmth."),
m("Ralph Lauren","Polo Explorer EDT","male",2019,3.72,["spring","summer"],["fresh","woody","citrus","aromatic"],"Explorer Polo. Juniper and sage. Adventurous."),
m("Marc Jacobs","Bang Bang EDT","male",2014,3.62,["spring","fall"],["fresh","woody","citrus","aromatic"],"Bang masculine. Pepper and cedar. Urban cool."),
m("Michael Kors","Extreme Blue EDT","male",2019,3.65,["spring","summer"],["aquatic","fresh","citrus","woody"],"Extreme blue. Sea and vetiver. Ocean masculine."),
m("Jimmy Choo","Illicit EDP","female",2015,3.75,["fall","winter"],["floral","sweet","amber","vanilla"],"Illicit. Peach and orchid. Secret pleasure."),
m("Viktor & Rolf","Bonbon EDP","female",2014,3.88,["fall","winter"],["caramel","sweet","gourmand","floral"],"Sweet candy luxury. Caramel and peach. Deliciously."),
m("Givenchy","Tres Irresistible EDP","female",2008,3.75,["spring","summer"],["floral","rose","fruity","musk"],"Very irresistible rose. Anise and rose. Playful."),
m("Givenchy","Dahlia Noir EDP","female",2011,3.88,["fall","winter"],["floral","woody","rose","musk"],"Black dahlia. Rose and patchouli. Mysterious beauty."),
m("Lancôme","Mille et Une Roses EDP","female",2013,3.85,["spring","fall"],["rose","floral","powdery","musk"],"Thousand roses. Rose and iris. Garden luxury."),
m("Lancôme","Magnifique EDP","female",2008,3.72,["spring","fall"],["floral","fruity","woody","musk"],"Magnifique. Rose and magnolia. French radiance."),
m("Boucheron","Quatre Pour Femme EDP","female",2014,3.75,["spring","fall"],["floral","woody","iris","musk"],"Quatre femme. Iris and cashmere. Jeweller feminine."),
m("Ferragamo","Signorina EDP","female",2013,3.72,["spring","fall"],["floral","fruity","rose","woody"],"Italian signature. Peony and currant. Fashionable."),
m("Ferragamo","Amo EDP","female",2017,3.75,["spring","fall"],["floral","fruity","sweet","white floral"],"Love letter. Rose and peach. Romantic Italian."),
m("Shiseido","Zen EDP","female",1964,3.88,["fall","winter"],["floral","oriental","amber","woody"],"Zen harmony 1964. Rose and sandalwood. Japanese."),
m("Adolfo Dominguez","Agua de Bambu EDT","unisex",2009,3.65,["spring","summer"],["fresh","green","woody","aromatic"],"Bamboo water. Fresh and natural. Spanish botanical."),
m("Loewe","001 Woman EDT","female",2015,3.68,["spring","fall"],["floral","musk","fresh","woody"],"001 her. Clean feminine. Spanish minimalism."),
m("Jil Sander","Pure EDT","female",2000,3.65,["spring","summer"],["floral","iris","fresh","musk"],"Jil pure. Clean iris. German minimalism luxury."),
m("Floris","Rose Absolute EDP","female",1960,4.12,["spring","summer"],["rose","floral","powdery","woody"],"English rose absolute. Pure rose. Timeless Mayfair."),
m("Penhaligon's","Ellenisia EDP","female",2012,3.88,["spring","fall"],["floral","iris","powdery","musk"],"Ellenisia. Iris and heliotrope. Victorian elegance."),
m("Czech & Czech","Heart of Gold EDT","unisex",2013,3.82,["fall","winter"],["floral","vanilla","sweet","musk"],"Heart gold. Jasmine and rose. Czech artisan luxury."),
m("Roger Vivier","Je T'Aime EDP","female",2019,3.88,["spring","fall"],["floral","rose","soft","musk"],"I love you. Rose and sandalwood. Shoe fashion."),
m("Houbigant","Fougere Royale EDT","male",1882,4.08,["fall","winter"],["fougere","lavender","oakmoss","coumarin"],"First fougere 1882. The original. Historical legend."),
m("Coty","Chypre EDP","female",1917,4.15,["fall","winter"],["chypre","floral","earthy","mossy"],"Original chypre 1917. The legendary 1917 creation."),
m("Dana","Tabu EDP","female",1932,3.82,["fall","winter"],["oriental","floral","spicy","earthy"],"Notorious 1932. Spiced oriental. Scandalous classic."),
m("Nina Ricci","Nina EDP","female",2001,3.55,["spring","summer"],["floral","fruity","sweet","fresh"],"Nina apple bottle. Sweet and innocent. Fairy tale."),
m("Lanvin","Eclat d'Arpage EDP","female",2002,3.72,["spring","fall"],["floral","fruity","fresh","powdery"],"Light and radiant. Peony and pear. French elegance."),
m("Mariah Carey","Always You EDT","unisex",2013,3.55,["spring","fall"],["floral","fresh","citrus","musk"],"Always you. Clean and accessible. Pop legend."),
m("Antonio Banderas","Blue Seduction for Women EDT","female",2007,3.55,["spring","summer"],["floral","aquatic","fresh","musk"],"Blue seduction her. Bergamot and jasmine. Accessible."),
m("Shakira","S EDP","female",2010,3.60,["spring","fall"],["floral","fruity","fresh","musk"],"Shakira S. Fresh and vibrant. Latin star."),
m("Hilary Duff","With Love EDP","female",2006,3.50,["spring","summer"],["floral","fruity","sweet","musk"],"With love. Magnolia and musk. Pop princess."),
m("Naomi Campbell","Cat Deluxe EDP","female",2006,3.55,["spring","fall"],["floral","fruity","sweet","musk"],"Cat luxury. Passion fruit and rose. Supermodel."),
m("David Beckham","Classic EDP","male",2014,3.58,["spring","summer"],["fresh","woody","citrus","aromatic"],"Classic Beckham. Refreshing and modern. Football icon."),
m("Avon","Incandessence EDP","female",2004,3.58,["spring","fall"],["floral","fruity","sweet","musk"],"Incandescent glow. Peony and apple. Warm luminosity."),
m("Bath & Body Works","Moonlight Path EDC","female",1995,3.55,["spring","fall"],["floral","musk","clean","fresh"],"Moonlit path. Soft musk and flowers. Clean classic."),
];

const existing=JSON.parse(readFileSync(DATA,"utf-8"));
console.log(`Mevcut: ${existing.length}`);
const seen=new Map(existing.map(p=>[`${p.brand}|${p.name}`.toLowerCase().trim(),true]));
let added=0;const merged=[...existing];
for(const p of N){
  const key=`${p.brand}|${p.name}`.toLowerCase().trim();
  if(!seen.has(key)){seen.set(key,true);merged.push(p);added++;}
}
merged.forEach((p,i)=>{p.id=String(i+1);});
writeFileSync(DATA,JSON.stringify(merged,null,2),"utf-8");
console.log(`Eklenen: ${added}`);
console.log(`Toplam: ${merged.length}`);
