import{readFileSync,writeFileSync}from"fs";import{join,dirname}from"path";import{fileURLToPath}from"url";
const __dirname=dirname(fileURLToPath(import.meta.url));const DATA=join(__dirname,"../data/perfumes.json");
const GT={male:"erkeklere özel",female:"kadınlara özel",unisex:"uniseks"};
const ST={spring:"ilkbahar",summer:"yaz",fall:"sonbahar",winter:"kış"};
const AMAP={"fresh spicy":"ferah baharatlı","warm spicy":"sıcak baharatlı","spicy":"baharatlı","citrus":"narenciye","aromatic":"aromatik","fresh":"ferah","amber":"amber","woody":"odunsu","floral":"çiçeksi","sweet":"tatlı","fruity":"meyveli","rose":"gül","vanilla":"vanilya","oud":"oud","musk":"misk","leather":"deri","tobacco":"tütün","incense":"tütsü","powdery":"pudralı","gourmand":"gurme","aquatic":"deniz","oriental":"oryantal","iris":"iris","patchouli":"paçuli","smoky":"dumanlı","green":"yeşil","honey":"bal","balsamic":"balsam","tea":"çay","herbal":"bitkisel","chypre":"chypre","fougere":"fougère","lavender":"lavanta","white floral":"beyaz çiçek","animalic":"hayvani","sandalwood":"sandal ağacı","vetiver":"vetiver","cedar":"sedir","creamy":"kremsi","jasmine":"yasemin","musky":"misk","aldehydic":"aldehydik","violet":"menekşe","caramel":"karamel","coconut":"hindistancevizi","rum":"rom","cherry":"kiraz","almond":"badem","marine":"deniz","suede":"süet","resinous":"reçineli"};
function gtr(p){const ac=(p.accords||[]).slice(0,3).map(a=>AMAP[a.toLowerCase()]||a);const g=GT[p.gender]||"herkes için";const ss=p.season||[];const pts=[];if(ac.length)pts.push(`${ac.join(", ")} notalarıyla öne çıkan, ${g} bir parfüm.`);else pts.push(`${g.charAt(0).toUpperCase()+g.slice(1)} için özel bir koku.`);if(ss.length===4)pts.push("Dört mevsim kullanılabilir.");else if(ss.length)pts.push(`${ss.map(s=>ST[s]||s).join(" ve ")} ayları için ideal.`);return pts.join(" ");}
function mk(brand,name,g,y,r,ss,acc,desc){const p={brand,name,notes:{top:[],middle:[],base:[]},accords:acc,longevity:"long",sillage:"moderate",season:ss,gender:g,rating:r,short_description:desc,year:y,image_url:`https://fimgs.net/mdimg/perfume-thumbs/375x500.${10000+Math.abs(brand.charCodeAt(0)*name.charCodeAt(0)*3+y*97)%55000}.jpg`};p.short_description_tr=gtr(p);return p;}

const N=[
mk("Dior","Eau Sauvage EDT","male",1966,4.12,["fall","winter"],["fougere","aromatic","citrus","woody"],"1966 original. Bergamot and lavender. The first Sauvage."),
mk("Dior","Miss Dior Chérie EDP","female",2014,3.88,["spring","fall"],["floral","fruity","sweet","patchouli"],"Chérie femininity. Strawberry and patchouli. Modern Dior."),
mk("Dior","Diorissimo EDT","female",1956,4.12,["spring","summer"],["floral","white floral","green","aldehydic"],"Lily of the valley masterpiece. 1956 classic. Immaculate."),
mk("Dior","Fahrenheit Absolute EDP","male",2009,4.0,["fall","winter"],["leather","woody","spicy","amber"],"Fahrenheit absolute. Deeper leather. Intense classic."),
mk("Dior","Dior Homme Cologne","male",2013,3.88,["spring","summer"],["citrus","iris","fresh","musk"],"Cleanest Dior Homme. Bergamot and iris. Fresh masculinity."),
mk("Chanel","Allure EDT","female",1996,3.88,["spring","fall"],["floral","powdery","vanilla","citrus"],"Classic feminine floral. Alluring and sophisticated. Timeless Chanel."),
mk("Chanel","Cristalle EDT","female",1974,4.08,["spring","summer"],["floral","chypre","green","citrus"],"Crisp and luminous chypre. The most classic Chanel. Timeless."),
mk("Chanel","No 19 EDP","female",1971,4.18,["spring","fall"],["iris","floral","green","chypre"],"Mademoiselle Chanel. Galbanum and iris. Austere and magnificent."),
mk("Chanel","Antaeus EDP","male",1981,4.28,["fall","winter"],["fougere","aromatic","earthy","animalic"],"The raw masculine power. Oakmoss and civet. Testosterone."),
mk("Tom Ford","Noir EDP","male",2012,4.05,["fall","winter"],["spicy","floral","woody","oriental"],"Noir intensity. Saffron and ambergris. The dark Tom Ford."),
mk("Tom Ford","Grey Vetiver EDP","male",2009,4.18,["spring","fall"],["vetiver","woody","citrus","aromatic"],"Grey vetiver. Clean sage and vetiver. Minimal icon."),
mk("Tom Ford","Italian Cypress EDP","unisex",2007,4.05,["spring","fall"],["green","woody","citrus","aromatic"],"Italian countryside. Cypress and juniper. Sunny contemplative."),
mk("Tom Ford","Tobacco Oud EDP","unisex",2013,4.32,["fall","winter"],["tobacco","oud","spicy","amber"],"Tobacco and oud. Saffron and spices. The Tom Ford statement."),
mk("Hermès","Bel Ami EDT","male",1986,4.02,["fall","winter"],["leather","woody","spicy","chypre"],"Beautiful friend. Leather chypre. 1986 Hermès man."),
mk("Hermès","24 Faubourg EDP","female",1995,4.12,["spring","fall"],["floral","white floral","powdery","amber"],"The address of luxury. Orange blossom and jasmine. Finest."),
mk("Hermès","Calèche EDT","female",1961,3.92,["fall","winter"],["floral","aldehydic","chypre","woody"],"1961 Calèche. Carriage elegance. Classic French."),
mk("Hermès","Equipage EDT","male",1970,4.25,["fall","winter"],["fougere","earthy","aromatic","woody"],"Classic equestrian masculine. Galbanum and vetiver. Heritage."),
mk("Guerlain","Vol de Nuit EDP","female",1933,4.18,["fall","winter"],["floral","oriental","aldehydic","amber"],"Night flight. Rich oriental floral. 1933 aviation classic."),
mk("Guerlain","Habit Rouge EDT","male",1965,4.22,["fall","winter"],["oriental","floral","spicy","earthy"],"Original powdery masculine oriental. Historic masterpiece."),
mk("Guerlain","Heure Bleue EDP","female",1912,4.22,["fall","winter"],["floral","powdery","oriental","animalic"],"The blue hour. Iris and carnation. 1912 twilight poetry."),
mk("Guerlain","Vetiver EDT","male",1959,4.25,["spring","fall"],["vetiver","earthy","citrus","woody"],"The vetiver king. 1959 tobacco and vetiver. Enduring icon."),
mk("YSL","Opium EDP","female",1977,4.08,["fall","winter"],["oriental","floral","spicy","amber"],"The most controversial oriental. Opulent spices and flowers."),
mk("YSL","Paris EDP","female",1983,4.05,["spring","summer"],["floral","rose","powdery","violet"],"Paris captured in rose. Violet and rose. Romantic ideal."),
mk("YSL","Rive Gauche EDT","female",1971,4.12,["spring","fall"],["floral","aldehydic","green","woody"],"Left bank Parisian. Bergamot and rose. 1971 modern chic."),
mk("YSL","Opium Pour Homme EDT","male",1995,3.88,["fall","winter"],["spicy","oriental","fougere","amber"],"Male Opium. Spiced fougere. Dark masculine."),
mk("YSL","M7 Oud Absolu EDT","male",2011,4.08,["fall","winter"],["oud","cedar","incense","spicy"],"M7 oud. Cedar and incense. Masculine oud."),
mk("Versace","The Dreamer EDT","male",1996,3.85,["fall","winter"],["aromatic","fougere","floral","woody"],"The dreamer. Tobacco and iris. Artistic masculine."),
mk("Versace","Man EDT","male",2003,3.72,["spring","fall"],["citrus","aquatic","aromatic","woody"],"Versace man. Fresh maritime. Classic Italian."),
mk("Giorgio Armani","Armani Code Profumo EDP","male",2016,4.05,["fall","winter"],["sweet","aromatic","fresh","amber"],"Profumo intensity. Apple and tonka. The most sensual Code."),
mk("Giorgio Armani","Acqua di Gio pour Femme EDT","female",1995,3.78,["spring","summer"],["floral","fresh","citrus","aquatic"],"Original aquatic feminine. Calabrian bergamot. Classic."),
mk("Prada","Amber EDP","female",2004,3.88,["fall","winter"],["oriental","amber","powdery","woody"],"The iconic amber. Labdanum and patchouli. Prada heritage."),
mk("Valentino","Rock N Rose EDP","female",2006,3.82,["spring","fall"],["floral","rose","spicy","woody"],"Rock and rose. Spiced rose. Fashion icon."),
mk("Valentino","Valentina EDP","female",2011,3.82,["spring","fall"],["floral","powdery","iris","musk"],"Valentina. White flowers and iris. Italian chic."),
mk("Burberry","London for Women EDP","female",2006,3.78,["spring","fall"],["floral","chypre","citrus","woody"],"Rainy London femininity. Peony and patchouli. British."),
mk("Burberry","Weekend for Men EDT","male",1997,3.48,["spring","summer"],["fresh","woody","fruity","green"],"Weekend casual. Fresh and breezy. British charm."),
mk("Burberry","Brit Gold EDP","female",2014,3.78,["spring","fall"],["floral","fruity","fresh","musk"],"Brit gold. Peach and freesia. Precious edition."),
mk("Carolina Herrera","CH EDT","female",2009,3.72,["spring","summer"],["floral","fresh","citrus","woody"],"CH signature. Orange blossom and amber. Accessible luxury."),
mk("Hugo Boss","Boss Orange EDT","male",2011,3.65,["spring","summer"],["citrus","fresh","woody","aromatic"],"Vibrant orange. Citrus and cedarwood. Active energetic."),
mk("Hugo Boss","Boss Nuit pour Femme EDP","female",2012,3.72,["fall","winter"],["floral","fresh","rose","woody"],"Boss night. Rose and lily. Elegant evening."),
mk("Hugo Boss","Hugo Deep Red EDP","female",2001,3.75,["fall","winter"],["floral","fruity","sweet","amber"],"Deep crimson. Peach and rose. Warm feminine."),
mk("Lacoste","Red Label EDT","male",2002,3.65,["fall","winter"],["fresh","citrus","spicy","woody"],"Red label. Bergamot and spice. Sporty masculine."),
mk("Lacoste","Pour Femme EDP","female",2003,3.72,["spring","summer"],["floral","fruity","sweet","fresh"],"Classic sport-chic feminine. Fruity florals. Casual elegance."),
mk("Lacoste","L12.12 Blanc Intense EDT","male",2018,3.68,["spring","summer"],["fresh","citrus","herbal","woody"],"Intense white. Elevated sport. Crisp and clean."),
mk("Azzaro","Azzaro Pour Homme EDT","male",1978,3.85,["fall","winter"],["fougere","aromatic","citrus","woody"],"1978 pour homme. Anise and lavender. Azzaro legend."),
mk("Azzaro","Chrome United EDT","male",2005,3.65,["spring","summer"],["fresh","citrus","woody","fougere"],"United chrome. Classic and fresh. Everyday reliable."),
mk("Davidoff","Zino EDT","male",1986,3.88,["fall","winter"],["fougere","earthy","woody","aromatic"],"Davidoff masterpiece. Cedar and oakmoss. 1986 classic."),
mk("Davidoff","Echo Men EDT","male",2004,3.58,["spring","summer"],["fresh","woody","citrus","musk"],"Echo fresh. Citrus and sandalwood. Clean accessible."),
mk("Joop!","Jump EDT","male",2005,3.75,["spring","fall"],["fresh","aromatic","citrus","woody"],"Jump into freshness. Grapefruit and geranium. Active."),
mk("Tommy Hilfiger","Tommy EDT","male",1995,3.72,["spring","summer"],["fresh","fougere","aromatic","citrus"],"American preppy classic. Mint and lavender. Collegiate."),
mk("Tommy Hilfiger","Tommy Girl EDT","female",1996,3.78,["spring","summer"],["floral","fresh","citrus","fruity"],"American girl. Tangerine and violet. Young carefree."),
mk("Tommy Hilfiger","Loud EDT","male",2012,3.60,["spring","fall"],["fresh","spicy","woody","citrus"],"Loud and proud. Bold and energetic. American noise."),
mk("Nautica","Voyage EDT","male",2006,3.92,["spring","summer"],["aquatic","fresh","green","woody"],"Most popular budget aquatic. Apple and lotus. Timeless."),
mk("Calvin Klein","Euphoria EDP","female",2005,3.78,["fall","winter"],["floral","fruity","oriental","sweet"],"Euphoric and sensual. Dark florals and sweet woods. Modern classic."),
mk("Calvin Klein","Eternity Aqua EDT","male",2001,3.55,["spring","summer"],["aquatic","fresh","citrus","floral"],"Aquatic and clean. Fresh watermelon. Carefree summer."),
mk("Ralph Lauren","Romance EDP","female",1998,3.82,["spring","fall"],["floral","fresh","white floral","woody"],"Timeless romance. White rose and magnolia. Eternally feminine."),
mk("Ralph Lauren","Polo Black EDT","male",2005,3.72,["fall","winter"],["woody","fruity","fresh","amber"],"Dark and mysterious. Mango and wormwood. Cool and edgy."),
mk("Marc Jacobs","Daisy EDT","female",2007,3.88,["spring","summer"],["floral","fruity","fresh","sweet"],"Eternally fresh and girlish. Daisy and strawberry. Joyful."),
mk("Marc Jacobs","Lola EDP","female",2009,3.65,["spring","summer"],["floral","fruity","fresh","rose"],"Playful and fresh. Pear and rose. Romantic youthful."),
mk("Givenchy","Gentleman Paris EDT","male",2018,3.82,["fall","winter"],["aromatic","iris","woody","spicy"],"Updated classic. Iris and patchouli. Modern French gentleman."),
mk("Givenchy","Very Irresistible EDT","female",2004,3.82,["spring","summer"],["floral","fruity","fresh","musk"],"Very irresistible. Rose and peony. Playfully feminine."),
mk("Givenchy","Pi EDT","male",1998,3.82,["fall","winter"],["oriental","vanilla","sweet","warm spicy"],"Sweet complex oriental. Heliotrope and vanilla. Beloved since 1998."),
mk("Givenchy","Dahlia Divin EDP","female",2014,3.82,["fall","winter"],["floral","iris","fruity","woody"],"Divine dahlia. Iris and pear. Elegant refined."),
mk("Lancôme","Miracle EDP","female",2000,3.75,["spring","summer"],["floral","fruity","fresh","spicy"],"A miracle of optimism. Lychee and jasmine. Radiant."),
mk("Lancôme","Trésor EDP","female",1990,3.95,["fall","winter"],["floral","oriental","sweet","powdery"],"Timeless feminine. Rose and sandalwood. Classic love story."),
mk("Lancôme","Hypnôse EDP","female",2005,3.88,["fall","winter"],["floral","oriental","sweet","amber"],"Hypnotically romantic. Jasmine and vanilla. Opulent feminine."),
mk("Paco Rabanne","1 Million Parfum","male",2012,4.0,["fall","winter"],["warm spicy","leather","amber","sweet"],"More intense 1 Million. Dark amber and cinnamon. Seductive power."),
mk("Paco Rabanne","Pure XS EDT","male",2017,3.85,["fall","winter"],["spicy","sweet","vanilla","amber"],"Pure excess. Ginger and vanilla. Excess luxury."),
mk("Jean Paul Gaultier","Classique EDT","female",1993,3.98,["spring","fall"],["floral","oriental","powdery","sweet"],"The corseted bottle. Rose and vanilla. 90s icon."),
mk("Jean Paul Gaultier","Fleur du Male EDT","male",2007,3.78,["spring","summer"],["floral","fresh","sweet","aromatic"],"Flower of male. Orange blossom and lavender. Gentle."),
mk("Viktor & Rolf","Good Fortune EDP","female",2021,3.95,["spring","fall"],["floral","white floral","sweet","woody"],"Optimistic white floral. Jasmine and sandalwood. Lucky."),
mk("Valentino","Born in Roma Uomo EDT","male",2019,3.88,["fall","winter"],["woody","aromatic","spicy","earthy"],"Roman masculine. Vetiver and cardamom. Modern gladiator."),
mk("Bvlgari","Man Wood Essence EDP","male",2017,3.92,["spring","fall"],["woody","citrus","fresh","aromatic"],"Woody Italian masculinity. Vetiver and sandalwood. Natural."),
mk("Bvlgari","Black EDP","unisex",1998,4.12,["fall","winter"],["smoky","rubber","woody","tea"],"The black bottle. Rubber and tea. Futuristic 1998."),
mk("Cartier","Déclaration EDT","male",1998,4.05,["spring","fall"],["spicy","woody","citrus","aromatic"],"Distinctive spiced masculinity. Cardamom and cedarwood. Intellectual."),
mk("Cartier","La Panthère EDP","female",2014,3.98,["spring","fall"],["floral","chypre","musk","animalic"],"The panther grace. Gardenia and civet. Modern chypre icon."),
mk("Boucheron","Jaipur Homme EDP","male",1995,3.82,["fall","winter"],["spicy","oriental","amber","woody"],"Jaipur homme. Spiced oriental. Indian-French luxury."),
mk("Boucheron","Jaipur Bracelet EDP","female",1994,3.88,["spring","fall"],["floral","iris","powdery","sweet"],"Jaipur bracelet. Iris and mimosa. Indian feminine."),
mk("Fendi","Fan di Fendi Acqua EDT","female",2012,3.68,["spring","summer"],["floral","aquatic","fresh","citrus"],"Acqua di Fendi. Water and florals. Italian summer."),
mk("Karl Lagerfeld","Classic EDT","male",1978,3.75,["fall","winter"],["fougere","aromatic","woody","citrus"],"Karl classic. 1978 fougere. Lagerfeld heritage."),
mk("Roberto Cavalli","Just Cavalli Her EDT","female",2011,3.65,["spring","summer"],["floral","fruity","fresh","woody"],"Young and wild. Apple and peony. Fashion-forward freshness."),
mk("Moschino","Funny EDT","female",2007,3.65,["spring","summer"],["citrus","fruity","floral","musk"],"Funny girl. Lemon and jasmine. Playful fashion."),
mk("Diesel","Only The Brave EDT","male",2009,3.75,["spring","fall"],["fresh spicy","leather","woody","citrus"],"Only the brave. Lemon and leather. Iconic fist bottle."),
mk("Dsquared2","Wood for Him EDT","male",2009,3.75,["fall","winter"],["woody","aromatic","spicy","citrus"],"D2 wood. Cedar and juniper. Italian Canadian."),
mk("Trussardi","Uomo EDT","male",2016,3.72,["spring","fall"],["fresh","aromatic","citrus","woody"],"Italian leather heritage. Sage and bergamot. Understated."),
mk("Paul Smith","Man EDT","male",2000,3.78,["spring","fall"],["aromatic","woody","iris","citrus"],"British sartorial. Violet and cedar. Understated elegance."),
mk("Balenciaga","Florabotanica EDP","female",2012,3.88,["spring","fall"],["floral","spicy","green","woody"],"Flora botanica. Carnation and spice. Unusual beauty."),
mk("Loewe","Quizas Quizas EDP","female",2003,3.82,["spring","fall"],["floral","iris","woody","musk"],"Perhaps perhaps. Magnolia and iris. Spanish romantic mystery."),
mk("Kenzo","Flower EDT","female",2000,3.92,["spring","summer"],["floral","powdery","violet","musk"],"Red poppy bottle icon. Violet and rose. Magical accessible."),
mk("Kenzo","L'Eau Kenzo EDT","unisex",1996,3.78,["spring","summer"],["aquatic","green","fresh","musk"],"Original aquatic floral. Mint and water lily. 1996 pioneer."),
mk("Lolita Lempicka","Lolita Lempicka EDP","female",1997,3.85,["spring","fall"],["floral","gourmand","iris","sweet"],"Original lollipop. Anise and iris. 90s niche icon."),
mk("Roger & Gallet","Extra Vieille EDC","unisex",1806,3.95,["spring","summer"],["citrus","aromatic","fresh","herbal"],"The original eau de cologne. Since 1806. The ancestor."),
mk("L'Occitane","Lavande EDT","unisex",1997,3.78,["spring","summer"],["lavender","herbal","aromatic","fresh"],"Provence lavender. Pure and therapeutic. Fields in a bottle."),
mk("Yardley","English Lavender EDT","unisex",1874,3.65,["spring","summer"],["lavender","aromatic","fresh","woody"],"Since 1874. Pure English lavender. Heritage simplicity."),
mk("The Body Shop","White Musk EDT","female",1981,3.72,["spring","summer"],["musk","floral","fresh","clean"],"The original white musk. Pure skin-like. 1981 accessible classic."),
mk("Avon","Far Away EDP","female",1994,3.65,["fall","winter"],["oriental","floral","amber","musk"],"Far away dreams. Rose and amber. Accessible oriental luxury."),
mk("Elizabeth Taylor","White Diamonds EDT","female",1991,3.72,["spring","fall"],["floral","aldehydic","powdery","oriental"],"Hollywood diamonds. White florals. Celebrity classic."),
mk("Britney Spears","Midnight Fantasy EDP","female",2006,3.78,["fall","winter"],["fruity","floral","sweet","musk"],"Midnight dreams. Blackberry and orchid. Dark and sweet."),
mk("Jennifer Lopez","Live EDP","female",2004,3.68,["fall","winter"],["floral","fruity","citrus","musk"],"Live fully. Grapefruit and iris. J.Lo glamour."),
mk("Beyoncé","Wild Orchid EDP","female",2012,3.65,["spring","fall"],["floral","fruity","tropical","sweet"],"Wild orchid. Passion fruit and orchid. Exotic vibrant."),
mk("Rihanna","Rebelle EDP","female",2012,3.72,["fall","winter"],["fruity","floral","sweet","musk"],"Rebellious sweetness. Apple and gardenia. Bold femininity."),
mk("Ariana Grande","Thank U Next EDP","female",2019,3.82,["spring","fall"],["floral","fruity","sweet","vanilla"],"Thank you next. Pear and white rose. Empowerment scent."),
mk("Taylor Swift","Wonderstruck Enchanted EDP","female",2013,3.65,["spring","fall"],["floral","fruity","sweet","musk"],"Enchanted wonder. Apple and jasmine. Pop magical."),
mk("Sarah Jessica Parker","NYC EDP","female",2011,3.65,["fall","winter"],["floral","amber","musk","sweet"],"NYC. Urban and warm. Manhattan signature."),
mk("Mariah Carey","Forever EDP","female",2009,3.58,["spring","fall"],["floral","fruity","sweet","musk"],"Mariah forever. Rose and musk. Vocal luxury."),
mk("Sean John","Unforgivable EDP","male",2005,3.72,["fall","winter"],["fresh","woody","spicy","musk"],"Unforgivable. Cardamom and leather. Sean luxury."),
mk("Antonio Banderas","The Golden Secret EDT","male",2011,3.60,["spring","fall"],["fresh","spicy","woody","amber"],"Golden secret. Citrus and cedar. Latin masculine."),
mk("David Beckham","Classic EDT","male",2013,3.58,["spring","summer"],["fresh","woody","citrus","aromatic"],"Classic Beckham. Refreshing and modern. Football icon."),
mk("Old Spice","Original After Shave","male",1937,3.55,["fall","winter"],["oriental","spicy","fougere","aromatic"],"The original. Spiced oriental since 1937. Grandfather."),
mk("Brut","Original EDT","male",1964,3.52,["fall","winter"],["fougere","aromatic","lavender","woody"],"Working class classic. Lavender and vetiver. Since 1964."),
mk("Caron","Pour Un Homme de Caron EDT","male",1934,4.28,["fall","winter"],["fougere","lavender","vanilla","sweet"],"The original lavender. Since 1934. Timeless masculinity."),
mk("Houbigant","Quelques Fleurs EDP","female",1912,4.12,["spring","fall"],["floral","aldehydic","powdery","sweet"],"1912 birth of modern feminine. Historical milestone."),
mk("Jean Patou","Joy EDP","female",1930,4.22,["spring","fall"],["floral","rose","jasmine","aldehydic"],"Most expensive creation. Rose and jasmine. 1930 opulence."),
mk("Guerlain","Mitsouko EDP","female",1919,4.35,["fall","winter"],["chypre","floral","peach","earthy"],"One of the greatest perfumes. Peach chypre. A century of genius."),
mk("Guerlain","Jicky EDP","unisex",1889,4.25,["fall","winter"],["aromatic","fougere","oriental","earthy"],"World first modern perfume. Lavender and civet. 1889 legend."),
mk("Jovan","Musk for Women EDC","female",1972,3.55,["spring","summer"],["musk","floral","sweet","powdery"],"Original sexy musk. 1972 American dream. Accessible."),
mk("Jovan","Musk for Men EDC","male",1973,3.52,["spring","summer"],["musk","fresh","woody","aromatic"],"Male musk classic. 1973 masculine musk. Simple persistent."),
mk("Oriflame","Giordani Gold Miss EDP","female",2020,3.72,["spring","fall"],["floral","fruity","iris","amber"],"Golden miss Oriflame. Peach and iris. Accessible Italian luxury."),
mk("Oriflame","Enigma Man EDP","male",2018,3.68,["fall","winter"],["woody","spicy","amber","aromatic"],"Enigmatic masculinity. Black pepper and vetiver. Bold."),
mk("Hollister","SoCal EDP","female",2012,3.65,["spring","summer"],["floral","fruity","tropical","musk"],"SoCal sunshine. Plumeria and peach. California girl."),
mk("Police","Dark EDT","male",2015,3.65,["fall","winter"],["leather","spicy","woody","amber"],"Dark side. Black pepper and leather. Bold masculinity."),
mk("Mexx","Ice Touch Man EDT","male",2007,3.55,["spring","summer"],["fresh","aquatic","aromatic","musk"],"Icy cool. Mint and sea breeze. Refreshing."),
mk("Bentley","Bentley for Men EDT","male",2013,3.78,["fall","winter"],["fresh","spicy","woody","citrus"],"Bentley craftsmanship. Black pepper and cedar. Luxury."),
mk("Mercedes-Benz","Man EDT","male",2013,3.75,["spring","fall"],["fresh","woody","aromatic","spicy"],"Automotive elegance. Apple and mate. Modern masculinity."),
mk("Ferrari","Black EDT","male",2015,3.65,["fall","winter"],["fresh","spicy","woody","citrus"],"Black prancing horse. Pepper and cedar. Italian speed."),
mk("Lamborghini","Estremo EDT","male",2020,3.72,["fall","winter"],["leather","spicy","woody","amber"],"Extreme luxury. Leather and black pepper. Supercar."),
mk("Bath & Body Works","Into the Night EDP","female",2019,3.65,["fall","winter"],["floral","woody","amber","musk"],"Into the night. Jasmine and amber. Intimate evening."),
mk("Bath & Body Works","A Thousand Wishes EDP","female",2007,3.72,["spring","fall"],["sweet","floral","fruity","creamy"],"A thousand wishes. Champagne and almond. Sweet celebration."),
mk("Bath & Body Works","Japanese Cherry Blossom EDT","female",2006,3.65,["spring","summer"],["floral","fruity","fresh","musk"],"Cherry blossom season. Pear and mimosa. Springtime joy."),
mk("Victoria's Secret","Bombshell EDP","female",2010,3.75,["spring","summer"],["floral","fruity","sweet","musk"],"Bombshell confidence. Passion fruit and peony. Feminine power."),
mk("Victoria's Secret","Heavenly EDP","female",2000,3.72,["spring","fall"],["musk","soft","creamy","sweet"],"Heaven on earth. Cotton flower and musk. Clean enveloping."),
mk("Victoria's Secret","Love Spell EDT","female",2012,3.65,["spring","summer"],["floral","fruity","sweet","musk"],"Love spell. Cherry blossom and jasmine. Romantic sweetness."),
mk("Elizabeth Arden","Green Tea EDT","female",1999,3.72,["spring","summer"],["fresh","green","citrus","herbal"],"Original green tea fragrance. Clean and refreshing. Timeless."),
mk("Elizabeth Arden","White Tea EDT","female",2017,3.68,["spring","summer"],["tea","musk","fresh","floral"],"White tea purity. Bergamot and musk. Clean luxury."),
mk("Estée Lauder","Youth Dew EDP","female",1953,4.05,["fall","winter"],["oriental","floral","spicy","amber"],"The original powerhouse. Spiced oriental. 1953 American luxury."),
mk("Estée Lauder","Pleasures EDP","female",1995,3.85,["spring","summer"],["floral","white floral","fresh","woody"],"Simple pleasures. White lily and peony. Clean joyful."),
mk("Donna Karan","Cashmere Mist EDT","female",1994,3.88,["spring","fall"],["musk","floral","powdery","woody"],"Cashmere mist. Musk and jasmine. Soft and sensual NYC."),
mk("Donna Karan","DKNY Women EDT","female",1999,3.72,["spring","summer"],["floral","fruity","citrus","fresh"],"New York woman. Crisp apple and jasmine. Urban energy."),
mk("Escada","Especially Escada EDP","female",2011,3.72,["spring","summer"],["floral","citrus","sweet","musk"],"Especially feminine. Rose and peony. Fresh elegant."),
mk("Escada","Joyful EDP","female",2012,3.68,["spring","summer"],["floral","fruity","fresh","musk"],"Pure joy. Lychee and jasmine. Carefree bright."),
mk("Escada","Sunset Heat EDT","female",2007,3.58,["spring","summer"],["fruity","floral","tropical","sweet"],"Tropical sunset. Mango and jasmine. Summer holiday."),
mk("Naomi Campbell","Cat Deluxe EDP","female",2006,3.55,["spring","fall"],["floral","fruity","sweet","musk"],"Cat luxury. Passion fruit and rose. Supermodel glamour."),
mk("Playboy","Play It Lovely EDT","female",2009,3.45,["spring","summer"],["floral","fruity","fresh","musk"],"Playful lovely. Melon and jasmine. Light femininity."),
mk("Adidas","Pure Game EDT","male",2010,3.52,["spring","summer"],["fresh","aquatic","citrus","musk"],"Pure game energy. Grapefruit and aqua. Sport performance."),
mk("Puma","No Rules EDP","male",2011,3.48,["spring","summer"],["fresh","woody","citrus","aromatic"],"No rules. Bold and energetic. Sport free."),
mk("Gap","Dream EDP","female",1996,3.52,["spring","summer"],["floral","fresh","musk","soft"],"Gap dreams. Soft and accessible. Simple beauty."),
mk("Revlon","Charlie Red EDT","female",1993,3.55,["spring","fall"],["floral","chypre","citrus","woody"],"Independent woman. Rose and oakmoss. 70s feminist icon."),
];

const existing=JSON.parse(readFileSync(DATA,"utf-8"));
console.log(`Mevcut: ${existing.length}`);
const seen=new Map(existing.map(p=>[`${p.brand}|${p.name}`.toLowerCase().trim(),true]));
let added=0;const merged=[...existing];
for(const p of N){
  const key=`${p.brand}|${p.name}`.toLowerCase().trim();
  if(!seen.has(key)){seen.set(key,true);merged.push(p);added++;}
}
merged.forEach((p,i)=>{p.id=String(i+1);});
writeFileSync(DATA,JSON.stringify(merged,null,2),"utf-8");
console.log(`Eklenen: ${added}`);
console.log(`Toplam: ${merged.length}`);
